### ISSUE TITLE
Mocking objects with generic metatype as a method parameter

### ISSUE THREAD

**Issue by szymesl** [MakeAWishFoundation/SwiftyMocky#102]
During development I have encountered a problem with mocking the objects with generic metatype like:

`func example<T>(with typeParam: T.Type)`

After mocking an object with function like the one above, the resulting generated Mock fails the build with error
`Swift Compiler Error (in Mock.generated.swift): Use of undeclared type ‘T’`

I would like to ask if the issue is known for you and if there is solution for the problem?

**Comment by amichnia** [comment]
@szymesl the problem should be already resolved. We are aware of that, and the fix is already on develop. 

It will be in upcoming release, tomorrow or friday - we will release either 2.0.0 or 1.0.3 (depending if we prepare all things needed for 2.0)

**Comment by szymesl** [comment]
Thank you for the fast reply! So I am looking forward to updating the SwiftyMocky.

**Comment by amichnia** [comment]
@szymesl - version 2.0.0 is swift and ready :) Feel free to check it out.

**Comment by szymesl** [comment]
Great news! Thank you very much!
