### ISSUE TITLE
Mock does not conform to protocol when functions differ only in their return type

### ISSUE THREAD

**Issue by andlang** [MakeAWishFoundation/SwiftyMocky#106]
There is a problem when a protocol has overloaded functions where the signatures differ only in their return type. For example:

```swift
//sourcery: AutoMockable
protocol FunctionsThatDifferOnlyInReturnType {
    func foo(bar: String) -> String
    func foo(bar: String) -> Int
}
```
In that case only for the first function a mock is created and the build fails since the generated class does not conform to the protocol.

Is there a solution for the problem, except of renaming one of the functions?

**Comment by Przemyslaw-Wosko** [comment]
@andlang 
Thanks for rising issue, i belive this was resolved, and we had this case covered in ingegration tests. 

We will try to fix this issue ASAP and release new minor version.

Just FYI, along with rised issues, you can also submit PR with failing tests for some unnusual cases :)

**Comment by amichnia** [comment]
@andlang - looking into it, will try to have it covered until beginning of next week

**Comment by amichnia** [comment]
OK, so this will require further concept work. First of all - even if we can avoid ambiguity by specifying return type, like:

```swift
let strVal: String = mock.foo(bar: "str") // method called that returns string
let intVal: Int = mock.foo(bar: "int")  // method called that returns int
```

That leaves us with question - what to do for perform and verify?

The typical usage will be:
```swift
Verify(mock, .foo(bar: .any))
```

Does it applies to both methods? Should it apply to both methods?

We can try some more advanced syntax for that particular case, like:

```swift
Verify(mock, .foo(bar: .any, returning: String.self))
Verify(mock, .foo(bar: .any, returning: Int.self))
```

What do you guys think?

**Comment by Przemyslaw-Wosko** [comment]
@andrzejmichnia the solution you proposed seems to be nice and clear, how about other return types, like tuple?

**Comment by andlang** [comment]
Thank you for replying so fast!
This solution with the `returning` parameter seems good for me!

**Comment by andlang** [comment]
Thank you! It works perfectly 😊
