### ISSUE TITLE
Build error with XCode 9.3 beta

### ISSUE THREAD

**Issue by andlang** [MakeAWishFoundation/SwiftyMocky#114]
I just tried SwiftyMocky with the newest XCode 9.3 beta. But I couldn’t compile it, since there is an ambiguous use of 'Matcher.register()' and 'Parameter.compare(lhs:rhs:with:)' when the parameters are arrays. I guess, this is related with changes in Swift 4.1.

**Comment by amichnia** [comment]
This is most probably reason. I don't have beta 9.3 now, and no way to get it. (I'm on cellular network for two weeks already, with no spare several GB ;) )

I'm planning to check it anyway, as soon as I sort my work environment.

**Comment by pgorzelany** [comment]
Are you planning to release a new pod version with this fix?

**Comment by Przemyslaw-Wosko** [comment]
@pgorzelany  
I'm currently working on automation improvements, to deliver updates as often as it's needed witout doing boring stuff. But in this case we can release minor version manually this evening.

**Comment by pgorzelany** [comment]
@Przemyslaw-Wosko Any chance for a new cocoapods release this week? I don't want to push but I can't run my tests on Xcode 9.3 because of those build errors and I don't want to revert to the old Xcode :)
