### ISSUE TITLE
swift templates broken with sourcery when using Xcode 9.3

### ISSUE THREAD

**Issue by kdawgwilk** [MakeAWishFoundation/SwiftyMocky#116]
I know this isn't really an issue with SwiftyMocky since the fix needs to happen in Sourcery but I wanted to bring it up over here since this where I got the swifttemplate from.  I also created an issue here  krzysztofzablocki/Sourcery#565

Error I get is here:
```
Using configuration file at '.sourcery-streetyapi.yml'. WARNING: Ignoring the parameters passed in the command line.
Scanning sources...
Found 116 types.
Loading templates...
Loaded 4 templates.
Generating code...
error: Error Domain=NSOSStatusErrorDomain Code=-1 "kCFStreamErrorHTTPParseFailure / kCFSocketError / kCFStreamErrorDomainCustom / kCSIdentityUnknownAuthorityErr / qErr / telGenericError / dsNoExtsMacsBug / kMovieLoadStateError / cdevGenErr: Could not parse the request/response. /  / custom to the kind of stream in question  /  / queue element not found during deletion /  / not a SysErr, just a placeholder  /  / General error; gray cdev w/o alert" UserInfo={terminationReason=__ObjC.NSTask.TerminationReason, error=dyld: Symbol not found: __T0s11_StringCoreV22isRepresentableAsASCIISbyFSbs6UInt16VcfU_
  Referenced from: /Users/<username>/Library/Caches/Sourcery/AutoMockable.swifttemplate/../SourceryRuntime.framework/Versions/A/SourceryRuntime
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /Users/<username>/Library/Caches/Sourcery/AutoMockable.swifttemplate/../SourceryRuntime.framework/Versions/A/SourceryRuntime
}
```

**Comment by Przemyslaw-Wosko** [comment]
Can you isolate code that is responsible for this crash?

**Comment by kdawgwilk** [comment]
Sourcery code?  Or swifttemplate code?

**Comment by kdawgwilk** [comment]
What I am currently doing to be able to still run 9.3 is to install 9.2 as well and set the cli tools to use the 9.2 e.g. `sudo xcode-select -s /Applications/Xcode9.2.app/Contents/Developer` that way even though I am building with 9.3 the sourcery run script still uses 9.2 or Swift 4.0

**Comment by amichnia** [comment]
Ok, guys, quick info. The good news are I just released SwiftyMocky 2.0.2 with all latest fixes (thanks a lot for input guys!!!)

The bad news are that Sourcery is not yet released for Swift 4.1. For now I prepared prebuilt sorcery for 4.1, but it is not final (use get_sourcery.sh 4.1 from SwiftyMocky folder). That means that it can work with flaws. 

One of the limitations is that we cannot have any comments inside mocked protocols definitions (treated as return types).

For my current project we made it run and work under Xcode 9.3, with that temporary solution, so if you can't wait to move to 9.3 - try it out.

**Comment by kdawgwilk** [comment]
Sourcery has now released `0.12` that was built with Xcode 9.3 Swift 4.1 but There are now compiler errors with the SwiftyMocky code generated using the new `0.12` release :(

**Comment by kdawgwilk** [comment]
Seeing weird stuff like this:
![screen shot 2018-04-11 at 3 49 49 pm](https://user-images.githubusercontent.com/7799267/38645069-0038a9ce-3da0-11e8-90b9-58a0bacc7f66.png)

**Comment by kdawgwilk** [comment]
Looks like this is only when using `@discardableResult` attributes, thankfully I can remove them but seems like a breaking change

**Comment by kdawgwilk** [comment]
Issue here krzysztofzablocki/Sourcery#596

**Comment by kdawgwilk** [comment]
I was unable to get the issue to reproduce in a controlled environment so I would say this issue is good to close out

**Comment by kdawgwilk** [comment]
I guess the reason I couldn't reproduce this was because you needed a `@discardableResult` attribute on a method that came after another method and I was only using one in my example so it wasn't happening.  But a fix was still added in this PR krzysztofzablocki/Sourcery#598
