### ISSUE TITLE
Could use a Release of current develop branch

### ISSUE THREAD

**Issue by Lifthanger** [MakeAWishFoundation/SwiftyMocky#122]
Dear Developers,

my project uses SwiftyMocky (which is great btw.).
Unfortunately we only use releases in our productive environment.
In order to use SwiftyMocky with Xcode 9.3 I could use the content of the current develop branch as a release.

Thanks!

**Comment by amichnia** [comment]
Hello, I need to retest latest changes a bit (guys fixed some additional problems - thanks!), but I think the release of 2.0.3 is an option. We don't have anything big pending, so it might be a good idea to have a stable 2.0.x release.

**Comment by Lifthanger** [comment]
Thanks for your help!
