### ISSUE TITLE
Mock property return value

### ISSUE THREAD

**Issue by GregoryMaks** [MakeAWishFoundation/SwiftyMocky#123]
I have found no way to mock property return value. There is `Given` macro for fuctions to stub their implementation, but is there a way to do the same thing with property getter?

So I have the following protocol:

```swift
//sourcery: AutoMockable
protocol AuthStorageProtocol {
    
    var isAuthorized: Bool { get }
    var currentAuthorizationModel: AuthorizationModel? { get }
    
    func save(authorizationModel model: AuthorizationModel)
    func clearAuthorizationModel()
    
}
```

I cannot stub the `currentAuthorizationModel` getter by using `Given` macro because inside generated code it just does:

```swift
var currentAuthorizationModel: AuthorizationModel? { 
	get {	invocations.append(.currentAuthorizationModel_get)
			return __currentAuthorizationModel }
	set {	invocations.append(.currentAuthorizationModel_set(.value(newValue)))
			__currentAuthorizationModel = newValue }
}
private var __currentAuthorizationModel: (AuthorizationModel)?
```

No reference to `methodReturnValues` to get the stubbed return value. Of course I can set the property value by using setter, but that would just make setter invocation check useless after that.

What are my options? Is this going to be developed? | Can I contribute with a PR? | Is this against the ideology of SwiftyMocky?

**Comment by amichnia** [comment]
@GregoryMaks hello, thanks for raising that issue. We had some discussion about that previously, and for now there is currently no Given for properties. 

For the current options - I will suggest using setter. It will of course raise the count of set invocations by 1, so the whole test will have to take it under consideration.

As for developing this in Mocky - we are always open for new ideas. For this situation I think all you need is aa accessor allowing to set property value without recording it in invocations list, to no to interfere with test itself.

The main problem here is that we decided, that Given should be kind of stable. So writing `Given(.authModel, willReturn: nil)` you expect that getter will always return this value. This is not true, as we can use setter (and most likely it would happen).

If any extension - I would suggest some "set initial state" kind of accessor for properties.

**Comment by amichnia** [comment]
@GregoryMaks as for the perform, you could use currently existing perform:

```swift
Perform(mock, .authModel(set: .any, perform: { ... }))
```

It should generate itself right now for all the setters as well.

As for setting initial value, Given would not be my first choice. I would rather say:

```swift
Prepare(mock, .authModel(with: <initial value>))
```

Remember, that the Mock.Give, Mock.Property, Mock.Verify... associated types are the ones holding knowledge about type, and assuring type safety.

**Comment by GregoryMaks** [comment]
@amichnia Yes, sure, I did mean to use already existing `Perform` method :).

About 
```swift
Prepare(mock, .authModel(with: <initial value>))
```
I do not think that storing data (initial value) inside the mock is a good idea. Mainly because it makes the mock object contain some logic beside simple verification and stubbing abilities.

**Comment by amichnia** [comment]
@GregoryMaks Given for properties is getting into SwiftyMocky 3.0 release. It's still being developed, but it will look something like:

```swift
Given(mock, .property(getter: 1))
```

It's also going to support sequences, so you can specify additional, subsequent default return values

```swift
Given(mock, .property(getter: 1, 2, 3))`
// mock.property -> 1
// mock.property -> 2
// mock.property -> 3
```

**Comment by GregoryMaks** [comment]
@amichnia Oh, that looks nice indeed. I did not work with sequences before and can hardly imagine will that be a good thing or complicate the understanding, but we'll see I guess 🙂.

Also about the implementation. I had a nearly-ready PR, but I did not manage to write Unit tests for it. If you are interested in what I've done you can take a look at the latest commits here https://github.com/GregoryMaks/SwiftyMocky/commits/develop and even take the code if it will be any of use for you. I hope it will.

Actually I did this because we needed property mocking in our project badly, but did not have time to finish the tests (as it usually happens in my life, sigh...).

**Comment by GregoryMaks** [comment]
And thanks for you have been doing so far, this is the best mocking framework for Swift out there! Simple and powerful as it should be.
