### ISSUE TITLE
Use Xcode extensions for inline mock generation

### ISSUE THREAD

**Issue by amichnia** [MakeAWishFoundation/SwiftyMocky#128]
Now the best approach to generate mock is to generate Mock.genereated.swift. Still, we do support inline generation, which opens additional possibilities.

For certain uses, it might be good to simplify generating these inline mocks, using xcode extensions. 

@Przemyslaw-Wosko what do you think?

**Comment by Przemyslaw-Wosko** [comment]
Could you tell little bit more about this process?
