### ISSUE TITLE
Xcode 10 sourcery compilation errors

### ISSUE THREAD

**Issue by pgorzelany-objectivity** [MakeAWishFoundation/SwiftyMocky#129]
Hi guys,

First of all, thank you for your hard work on this project. It is a delight to work with and it has saved writing so much boilerplate code for me and my team.

Everything was working fine with Xcode 9 but after upgrading to Xcode 10 we are hitting what seems to be a Sourcery runtime error:

error: Error Domain=NSOSStatusErrorDomain Code=-1 "kCFStreamErrorHTTPParseFailure / kCFSocketError / kCFStreamErrorDomainCustom / kCSIdentityUnknownAuthorityErr / qErr / telGenericError / dsNoExtsMacsBug / kMovieLoadStateError / cdevGenErr: Could not parse the request/response. /  / custom to the kind of stream in question  /  / queue element not found during deletion /  / not a SysErr, just a placeholder  /  / General error; gray cdev w/o alert" UserInfo={terminationReason=__ObjC.Process.TerminationReason, error=dyld: Symbol not found: __T0BOWV

Is this a known issue? Do you know any workarounds?

**Comment by amichnia** [comment]
@pgorzelany-objectivity  I've been looking into it, I can't compile Sourcery in XCode 10 right now, so this is still open. There are several issues, also fo Sourcery dependencies. Some are due to the new compiler (it has problems with literals, that seems to be too complicated, lol). I already posted my foundings in Sourcery issue, we will see.

**Comment by pgorzelany-objectivity** [comment]
@amichnia I can confirm that after executing:
`sh ./Pods/SwiftyMocky/get_sourcery.sh 4.2-xcode10`
and deleting the cache folder of Sourcery the Sourcery runtime errors went away.

The project is still not compiling since I am now hitting https://github.com/MakeAWishFoundation/SwiftyMocky/issues/124

As a side note, the --disableCache flag was not sufficient to remove Sourcery runtime errors. Only after deleting Sourcery cache folder did the errors stopped appearing.

**Comment by amichnia** [comment]
@pgorzelany-objectivity have you tried to use `release/3.0` branch? It's still in progress, but as I recall fix for #124 should be already there, waiting for 3.0 to be released

**Comment by pgorzelany-objectivity** [comment]
@amichnia using the release/3.0 and get_sourcery.sh 4.2-xcode10 fixed all issues.Waiting for the 3.0 release than :)

**Comment by amichnia** [comment]
We released 2.1.0 with Xcode 10 support. 3.0 will come soon. Branch `release/3.0` would be removed soon.
