### ISSUE TITLE
Fail test instead of crash for no given value etc.

### ISSUE THREAD

**Issue by amichnia** [MakeAWishFoundation/SwiftyMocky#132]
Right now we are crashing tests when given is not specified. We should fail the test with a descriptive message instead.

**Comment by Przemyslaw-Wosko** [comment]
General workaround for xcode to fail test without crash and handling not stubbed mocks with nice error handling is done. Whats left are minor improvements for methods that throws and protocol with initializers. I think we might want to close this issue and create another ones for future versions.
