### ISSUE TITLE
Fix: Protocols with generic methods

### ISSUE THREAD

**Issue by SergeyKovalenko** [MakeAWishFoundation/SwiftyMocky#138]
Mock is not generated properly for such a protocol using SwiftyMocky (2.0.3):
```swift
struct Mytest<Key, Value> {
  let value: Value
  let key: Key
}

protocol ProtocolWithGenericType: AutoMockable {
  func sorted<Key, Value>(by key: Mytest<Key, Value>)
}
```
however, it works for:

```swift
protocol ProtocolWithGenericType: AutoMockable {
  func sorted<Key, Value>(by key: Dictionary<Key, Value>)
}
```
Is there any limitation for generic methods?

**Comment by amichnia** [comment]
@SergeyKovalenko  Thanks for keeping us busy :) To answer your question, there are still unfortunately some limitations. Sourcery does not fully handle generic methods/constraints (yet?), although they added a lot in this area recently. 

That means we have to do some parsing on our own, and with limited data (we have not tested every possible case), it leaves rooms for errors. Above is clear example of us missing few cases.
