### ISSUE TITLE
Mocking functions with unnamed parameters results in compilation errors

### ISSUE THREAD

**Issue by arrrnas** [MakeAWishFoundation/SwiftyMocky#139]
```
protocol FailsWithUntagged {
    func foo(_: String, bar: String)
}
```
results in 
```
...
    fileprivate enum MethodType {
        case ifoo__barbar:(Parameter<String>)
...
```
which is an invalid enum case since it has a colon at the end.

```
⇒  /usr/local/bin/sourcery --version
0.15.0
```
using `SwiftyMocky 2.1.0`

**Comment by amichnia** [comment]
@arrrnas thanks for raising this, we were missing some edge cases. As all of these small issues, I will include it in 3.0.0

**Comment by Przemyslaw-Wosko** [comment]
Seems like its done in #142
