### ISSUE TITLE
Mocking functions with parameters named "for" result in compilation errors

### ISSUE THREAD

**Issue by arrrnas** [MakeAWishFoundation/SwiftyMocky#140]
```
protocol FailsWithFor {
    func foo(for: String)
}
```
results in 
<img width="960" alt="screen shot 2018-09-28 at 7 33 23 pm" src="https://user-images.githubusercontent.com/16186741/46221311-6ccfe300-c355-11e8-894d-4f3318748da5.png">
<img width="1013" alt="screen shot 2018-09-28 at 7 34 13 pm" src="https://user-images.githubusercontent.com/16186741/46221346-82450d00-c355-11e8-9024-a2d0fb6ef8bf.png">
```
⇒  /usr/local/bin/sourcery --version
0.15.0
```
using `SwiftyMocky 2.1.0`

**Comment by amichnia** [comment]
@arrrnas thanks for raising this. This is probably problem that will be caused by any keyword. While it should be avoided, we would have to handle this case.

**Comment by Przemyslaw-Wosko** [comment]
Seems like its finished. #142
