### ISSUE TITLE
Refactor swifttemplate

### ISSUE THREAD

**Issue by Przemyslaw-Wosko** [MakeAWishFoundation/SwiftyMocky#144]
Our swifttemplate, file that is responsible for mocks generation is 1700 lines long. Thats pretty bad for future improvements, it doesn't really slow us down right now, but might be an issue in future.

We have to find a way with Sourcery contributors, to be able use code from external libraries in swifttemplate. That way we would be able to reduce this file and write some tests for those classes.

**Comment by amichnia** [comment]
We also need actual tests for template itself. Right now we just build and test if output compiles, but this always opens room for errors. With some more structured approach we will be just able to test all possible scenarios (or near to it).

**Comment by laxmorek** [comment]
According to this [examples](https://github.com/krzysztofzablocki/Sourcery/tree/master/SourceryTests/Stub/SwiftTemplates) it is possible to import one template into another (inline). Importing swift files it is possible too.

I discussed about it with @Przemyslaw-Wosko via Hangouts. We will handle this refactoring.
