### ISSUE TITLE
`No such module 'Sourcery'` build error message.

### ISSUE THREAD

**Issue by laxmorek** [MakeAWishFoundation/SwiftyMocky#150]
**Info**
Project doest not compile when I add `SwiftyMocky` via CocoaPods only to Test Target.

**Error message:**

<img width="730" alt="zrzut ekranu 2018-10-6 o 16 31 49" src="https://user-images.githubusercontent.com/4774319/46572423-b9cf3d00-c985-11e8-8ff2-54ba40164ba7.png">

**Podfile:**
```ruby
def install_pods
   # other_pods    

    pod 'Sourcery', '0.15.0'
end

target 'TARGET_NAME' do
    install_pods
end

target 'TARGET_NAME_TESTS' do
    install_pods
    
    pod 'SwiftyMocky', '3.0.0'
end
```

**Workaround:**
Problem does not occur when I change my `Podfile ` to:
```ruby
def install_pods
   # other_pods    

    pod 'Sourcery', '0.15.0'
end

target 'TARGET_NAME' do
    install_pods
    
    pod 'SwiftyMocky/Custom', '3.0.0'
end

target 'TARGET_NAME_TESTS' do
    install_pods
    
    pod 'SwiftyMocky', '3.0.0'
end
```
or
```ruby
target 'TARGET_NAME' do
    # other_pods   

    pod 'Sourcery', '0.15.0'
    pod 'SwiftyMocky', '3.0.0'
end
```

**Expected behavior** 
I want to add `SwiftyMocky` only to my Test Target without any compile errors.

**Comment by repl-ullas-ml** [comment]
@laxmorek May be adding -DMocky as the other swift flags shall resolve this issue.

**Comment by amichnia** [comment]
@laxmorek I tried to reproduce that but did not succeed. This is Podfile I used:

```ruby
platform :ios, '9.0'
use_frameworks!

def install_pods
   # other_pods

    pod 'Sourcery', '0.15.0'
end

target 'TestApp' do
    install_pods
end

target 'TestAppTests' do
    install_pods

    pod 'SwiftyMocky', '3.0.0'
end
```

I was able to use it with success, generate mocks, etc.

There are several things you might check:
 - as @repl-ullas-ml mentioned, verify if -DMocky is set in flags, maybe you somehow hide/override it. It is required, as there are unfortunately leftovers from sourcery template in Mock.generated (including import Sourcery)
 - do not add 'Sourcery' in the import section in config yml. Sourcery does not have any module you might import in app/test target.

For now, it does not seem as a SwiftyMocky issue, but feel free to reopen it if nothing of the above helps.
