### ISSUE TITLE
Better assertions error messages. 

### ISSUE THREAD

**Issue by laxmorek** [MakeAWishFoundation/SwiftyMocky#151]
We can take an example from `Quick/Nimbe` lib:
<img width="1378" alt="zrzut ekranu 2018-10-3 o 20 54 16" src="https://user-images.githubusercontent.com/4774319/46572691-775c2f00-c98a-11e8-8f0e-c2f75f7b8130.png">

At the moment `SwiftyMocky` generates hard to understand communicates:
<img width="1390" alt="zrzut ekranu 2018-10-3 o 20 54 08" src="https://user-images.githubusercontent.com/4774319/46572707-ab375480-c98a-11e8-82f7-c5646ee4f487.png">

**Comment by g-amichnia** [comment]
Done in 4.0.0
