### ISSUE TITLE
Consider adding SwiftLint.

### ISSUE THREAD

**Issue by laxmorek** [MakeAWishFoundation/SwiftyMocky#153]
Consider adding SwiftLint.
https://github.com/realm/SwiftLint

Which rules should be turned on?

**Comment by Przemyslaw-Wosko** [comment]
I do not approve adding this tool for this codebase for 2 reasons: 
- having SwiftLint for 10 classes looks like overkill
- There is no need to Lint tests or generated template, because too few rules we might actually use :/ 

In my honest opinion, having this tool here will be only burden.

**Comment by laxmorek** [comment]
That was only considerations. I understand your arguments and I agree with them. :)
