### ISSUE TITLE
`weak` attribute in protocols 

### ISSUE THREAD

**Issue by laxmorek** [MakeAWishFoundation/SwiftyMocky#154]
Future releases of Swift will not support `weak` attribute in protocols declaration. We should handle it to keep project buildable. 

<img width="1320" alt="zrzut ekranu 2018-10-6 o 18 44 36" src="https://user-images.githubusercontent.com/4774319/46573588-e2603280-c997-11e8-9839-e1f225b252ba.png">

source: `SwiftyMocky/SwiftyMocky-Example/Shared/Example 1/SimpleProtocols.swift`

**Comment by Przemyslaw-Wosko** [comment]
Instead of creating new issue, i'd propose to add comment to existing issue, look at #71. 
Closing in favour of already opened issue.
