### ISSUE TITLE
Verify poperty setup

### ISSUE THREAD

**Issue by Przemyslaw-Wosko** [MakeAWishFoundation/SwiftyMocky#159]
Swifty mocky doesn't recognize invocation, when generated Verify constructor used without parameters, its seems like minor bug. 

Protocol: 
```
protocol SomeProtocol { 
var someProperty: ((String) -> ())? { get set } 
}
```

lets say i want to test, if my class under test setup callback for another dependency
```
sometingThatImplementsSomeProtocol.someProperty = { string in ... } 
```
and i want to test it: 
```
Verify(sometingThatImplementsSomeProtocol, .someProperty)
```
Test will fail on this line, because it doesn't recognize this invocation

```
Verify(sometingThatImplementsSomeProtocol, .someProperty(set: .any))
```
This will pass, i think we might want to fix this behaviour.

**Comment by amichnia** [comment]
@Przemyslaw-Wosko These are two different `Verify` cases. First one is for getter, second is for setter:

```
mock.name = "Danny" // setter
mock.name = "Joanna" // setter

print(mock.name) // getter

// Verify getter:
Verify(mock, 1, .name)
// Verify setter:
Verify(mock, 2, .name(set: .any))
Verify(mock, 1, .name(set: .value("Danny")))
Verify(mock, .never, .name(set: .value("Bishop")))
```

So actually it seems the behaviour seems correct:

`Verify(sometingThatImplementsSomeProtocol, .someProperty)`

is checking if you ever used getter on that property.

The case is, that we have a nice thing `.someProperty(set: ...)` for setters, while making it `.someProperty(get: ???what here??)` seemed unnatural. So, after all, I decided to use property name for getters, and parametric version for setters.

Could you check and confirm if that is fine?

**Comment by amichnia** [comment]
OK, hopes that clarified topic, closing.
