### ISSUE TITLE
Compilation error with generic function that throws

### ISSUE THREAD

**Issue by TimeDelta** [MakeAWishFoundation/SwiftyMocky#163]
I have a function in a mocked protocol (NumericSampleUtil) declared as such:
```swift
func max<Type: Comparable>(for attribute: Attribute, over samples: [Sample], per aggregationUnit: Calendar.Component?)
throws -> [(date: Date?, value: Type)]
```

Note that the only way for the compiler to infer the type of `Type` is by the return type.

When SwiftyMocky generates the `Given: StubbedMethod` subclass for `NumericSampleUtilMock`, it does the following:

```swift
static func max<Type: Comparable>(for attribute: Parameter<Attribute>, over samples: Parameter<[Sample]>, per aggregationUnit: Parameter<Calendar.Component?>, willThrow: Error...) -> MethodStub {
    return Given(method: .m_max__for_attributeover_samplesper_aggregationUnit(`attribute`, `samples`, `aggregationUnit`), products: willThrow.map({ Product.throw($0) }))
}
```

However, there is no return type for the compiler to use when trying to discern what `Type` should be. This causes the following compilation error: `Generic parameter 'Type' is not used in function signature`

Unfortunately, I'm not really sure how or even if this can be fixed because the return type is the only place that `Type` is used. I was thinking it might be possible to add an extra parameter to the generated function in that case right before the `willThrow` parameter but am not sure how to even go about doing that.

For now, I can just add another "dummy" parameter into the method definition on the protocol that allows the compiler to determine what `Type` should be but it would be nice if I didn't have to do that.

Any help would be greatly appreciated. Thanks in advance.

**Comment by amichnia** [comment]
Your intuition is correct, this is probably special case we will have to handle, by adding parameter just to infer type. 

I added it to 3.1 fixes, but we are both (me and Przemek) so busy with work, that I cannot guarantee we will takle it with next release

**Comment by amichnia** [comment]
@TimeDelta This goes to version 4.0. I inspected the issue and there are more things to refactor with generics inferred from return type. Doing it now would require too much hacky workarounds, I'd prefer to do it later, with proper unit testing and stuff.

**Comment by TimeDelta** [comment]
No rush. I'd rather wait and have it done right. Thanks for the update.

**Comment by g-amichnia** [comment]
So the current state is: we would be using only subset of generics, that are present in method parameters. That would make it compile, but it would not be possible to make method throw or not throw basing solely on inferred return type. So:

```swift
// func method<T>(_ p: Int) -> T
Given(mock, .method(.any, willThrow: SomeError))

let a: Int = mock.method(1) // throws
let a: String = mock.method(1) // throws
```
