### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by coryroloff** [MakeAWishFoundation/SwiftyMocky#165]
Hello,

I was wondering if there are plans to support the Swift package manager? Apologies if it’s been asked before. I didn’t see any tickets referencing it though.

Thanks!

**Comment by Przemyslaw-Wosko** [comment]
Hi, 
First of all do you have any particular need to use SwiftyMocky with SPM?  What is the reason that you asking for it.

On the other hand - currenltly we think about supporting linux platform and go for server side Swift. 
That would require SPM support and its just a matter of time.

**Comment by Przemyslaw-Wosko** [comment]
I'm glad that you love it 😊 
If you will have a need to integrate our library with SPM, then we can work on this. Just give us heads up that you will need this for sure. For now we have urgent needs for automation testing of Carthage integration and fixing bugs for generics.

For futher discussions please join our Slack ;)

**Comment by amichnia** [comment]
@coryroloff @Przemyslaw-Wosko I already checked SPM (ani Mint) integration topic. I would love to see it done, but there is some impediment - we are using swifttemplate, which does not work with SPM. I see some options to overcome it, but as Przemek said, we have some fixes to do, and we already delayed with release.

So, to sum up, enabling spm and mint is a bigger topic I will definitely address. Stay tuned :)

**Comment by amichnia** [comment]
@coryroloff @Przemyslaw-Wosko I just found that the limitation for Sourcery swifttemplates disappeared. It is very likely, that 4.0 will introduce support for SPM and Mint :)

**Comment by amichnia** [comment]
Will be in the next release (3.3)

**Comment by artur-zaremba** [comment]
Hi, sorry but I can't find how to use it with spm packages testing, also I didn't find any mentions in documentation. Can I use SwiftyMocky to setup spm test targets?

**Comment by amichnia** [comment]
@artur-zaremba we don't have dedicated documentation for that yet. It's on my todo list.

Another problem is, that generation will work on macOS only.

As for the tests themselves, we have integration tests library, here's SwiftPM integration for unit tests: https://github.com/MakeAWishFoundation/SM-Integration-Tests/tree/master/SwiftPM

Feel free to look at `Package.swift` there to check how we integrated SwiftMocky there for example project. Also, have a brief look into `Mockfile` if you want to generate mocks for SwiftPM project.
