### ISSUE TITLE
`File 'Mock.generated.swift' is part of module 'Companion'; ignoring import` warning

### ISSUE THREAD

**Issue by laxmorek** [MakeAWishFoundation/SwiftyMocky#168]
I am using `SwiftyMocky` via CocoaPods. According to `podspec` file I can use `SwiftyMocky` as `Core` and `Custom`. 

I assumed that `Core` is for tests targets and `Custom` is for non-test targets (please correct me if I am wrong).

According to above assumptions my `Podfile`:
```ruby
target 'Companion' do
    install_pods
    pod 'SwiftyMocky/Custom', '3.1.0'
end

target 'CompanionTests' do
    install_pods
    pod 'Nimble', '7.3.1'
    pod 'SwiftyMocky', '3.1.0'
end
```

Everything works fine but it generates annoying Xcode warning:

<img width="1508" alt="zrzut ekranu 2019-01-31 o 12 13 56" src="https://user-images.githubusercontent.com/4774319/52050914-4b287780-2552-11e9-93d7-329dd9334008.png">

I would like to create a PR which removes `@testable import Companion` from 'SwiftyMocky/Custom' but before that I would like to ask your for opinion.

**Comment by amichnia** [comment]
@laxmorek good point. I think removing it might be a good idea.

While you can use `SwiftyMocky/Custom` for prototyping (we did it once and seems to kind of work), please be careful, as it was never intended to be used in production codebase. 

I think we will rename it to `SwiftyMocky/Prototyping`, or create another subspec just for that case.

**Comment by laxmorek** [comment]
I can rename it in my PR, what do you think? Should we wait or do it now? :)

**Comment by laxmorek** [comment]
MR with fix has been merged.
