### ISSUE TITLE
Skipping *.generated.swift for code generation

### ISSUE THREAD

**Issue by amichnia** [MakeAWishFoundation/SwiftyMocky#17]
As @CurlyHeir mentioned - Mock.generated.swift could be quite big, making future generations slower if being scanned as well.

We should probably exclude all *.generated.swift files from scanning by default.

**Comment by amichnia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclude *.generated.swift from scanning](https://trello.com/c/VokUobln/26-exclude-generatedswift-from-scanning)

**Comment by amichnia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exclude *.generated.swift from scanning](https://trello.com/c/VokUobln/26-exclude-generatedswift-from-scanning)

**Comment by krzysztofzablocki** [comment]
Sourcery automatically skips files that are generated by it :)

**Comment by amichnia** [comment]
Thanks for the info, that really solves some problem for us :) 
Is it like that for all `*.generated.swift` files? In one of our projects, we were using RSwift, which produced quite big `R.generated.swift` files, and so whole generation process time increased.

**Comment by krzysztofzablocki** [comment]
it will skip Sourcery generated files, name isn't taken into consideration at all, its just that all Sourcery files have the header saying they were generated by the tool and so skipped, if you want to skip other generated files then you'd need to use exclude manually

**Comment by amichnia** [comment]
Let's test exclude against R.generated.swift, and add some info in documentation. Seems that it's all needed to close that.

**Comment by amichnia** [comment]
done
