### ISSUE TITLE
Generated classes should be public by default

### ISSUE THREAD

**Issue by mpdifran** [MakeAWishFoundation/SwiftyMocky#170]
Generated classes should be `public` by default (or at least configurable). The use case is I have a framework that exposes some protocols that need to be mocked for tests. Since I can't have the containing app generate the mocks for the framework, I need to expose a test framework containing the framework's generated mocks. This is not useful unless the mocks are `public`.

I don't see any reason why you wouldn't want your mocks to be public, so the solution should be as simple as adding `public` to all classes. 

I can take a crack at implementing this.

**Comment by mpdifran** [comment]
There is currently a workaround where you can `@testable import` the framework, but I still think this change should be made.

**Comment by amichnia** [comment]
@mpdifran Funny, I literally have the same case right now :) I have a closed source framework that is distributed with public interfaces mocks (in separate module).

As you said, `@testable import MyFrameworkMocks` is a good workaround. But you are right, that there should be no issue with making stuff public. 

I will add it to configuration then, still I'm not sure whether public should be default or not. @Przemyslaw-Wosko  what do you think?

**Comment by Przemyslaw-Wosko** [comment]
@amichnia i think that you are right! make things public doesn't hurt, but i'd use `open` instead of `public`

**Comment by mpdifran** [comment]
Ok, I'll update the PR to use `open` instead.

**Comment by amichnia** [comment]
Merged PR from @mpdifran - closing this
