### ISSUE TITLE
'SwiftyMocky/SwiftyMocky-Swift.h' file not found when use_modular_headers! globally in Podfile (cocoapods 1.6.0.beta.2)

### ISSUE THREAD

**Issue by trimonovds** [MakeAWishFoundation/SwiftyMocky#173]
We use latest at the moment version of Cocoapods (1.6.0.beta.2) and use_modular_headers! flag is set globally. When build process starts we get Lexical or Preprocessor issue - 'SwiftyMocky/SwiftyMocky-Swift.h' file not found in MockySetup.m. Changing #import <SwiftyMocky/SwiftyMocky-Swift.h> to #import "SwiftyMocky-Swift.h" solves the problem. Is there an opportunity to support use_modular_headers flag?

**Comment by trimonovds** [comment]
We've tried to set ":modular_header => false" for 'SwiftyMocky' but it doesn't work too.

**Comment by trimonovds** [comment]
> We use latest at the moment version of Cocoapods (1.6.0.beta.2) and use_modular_headers! flag is set globally. When build process starts we get Lexical or Preprocessor issue - 'SwiftyMocky/SwiftyMocky-Swift.h' file not found in MockySetup.m. Changing #import <SwiftyMocky/SwiftyMocky-Swift.h> to #import "SwiftyMocky-Swift.h" solves the problem. Is there an opportunity to support use_modular_headers flag?

**Comment by amichnia** [comment]
@trimonovds I need to check how to do it right. It might require some additional configuration, but maybe I'll find some generic solution. Thanks for raising it up!

**Comment by trimonovds** [comment]
Thanks! I look forward to the update

**Comment by amichnia** [comment]
@trimonovds It seems that it should be enough to set "defines module" to true for the SwiftyMocky target. I will add this to podspec.

It will be part of the 3.1.1, but I still need to test it and see if it solves the issue.

**Comment by amichnia** [comment]
Ok, after retesting. From 3.1.1 (currently on develop):

1. Either use post installer actions to add 'GCC_PREPROCESSOR_DEFINITIONS' => 'STATIC_LIBRARY=1'
2. Or use subspec 'SwiftyMocky/StaticLibrary' when you don't want to `use_frameworks` in the podfile

It would be part of the next release, you can check if it solves the problem using develop branch

**Comment by trimonovds** [comment]
Thanks @amichnia! SwiftyMocky rocks!=)
