### ISSUE TITLE
Better handling Matcher issues

### ISSUE THREAD

**Issue by amichnia** [MakeAWishFoundation/SwiftyMocky#174]
Currently, all matcher errors are printed to console only. As we have some kind of test observer now, we should be able to show them in the context of the test at least.

**Comment by amichnia** [comment]
Should be done together with #151

**Comment by DanSkeel** [comment]
What about given opportunity for a `matching` case closure to report the description of mismatch? For example if i'm matching an array of objects that are not Equatable, I could describe the cause of mismatch. For example by throwing a LocalizedError.

We could change match `case matching((ValueType) -> Bool)` to `case matching((ValueType) throws -> Void)`
