### ISSUE TITLE
Handling Self as generic parameter for return type

### ISSUE THREAD

**Issue by spaluchiewicz** [MakeAWishFoundation/SwiftyMocky#175]
Mock generated for below protocol is not correct due to fact that Self isn't mapped into type.
Is it possible to force this mapping with current SwiftyMocky version? 
(If not is there a plan to include this on feature list for upcoming release?)

```swift
//sourcery: AutoMockable
protocol NotMockedObjectProtocol: class {
    func methodWillReturnSelfTypedArray() -> Array<Self>
}
```

**Comment by amichnia** [comment]
@spaluchiewicz I would like to see it working, it is on the pipeline for 4.0. We are somehow delayed with releases, so I can't give now a concrete date, but I already started working on it.

**Comment by spaluchiewicz** [comment]
@amichnia great! I look forward to hear/see update on this.

**Comment by amichnia** [comment]
@spaluchiewicz it is done, would be a part of 3.3 release
