### ISSUE TITLE
'Product' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by pballart** [MakeAWishFoundation/SwiftyMocky#178]
Hello! I am trying SwiftyMocky in a project and found a problem.
I have a protocol that I want to be mocked. It defines a function which takes a parameter of type `Product`. This `Product` is a struct defined in a third-party framework which is imported to the project. I defined in the `mocky.yml` file to import it as well for the `Mock.generated.swift` file.

The mocks get generated correctly but there is an error because SwiftyMocky also defines a `Product` enum in the `Stubbing.swift` class so the compiler doesn't know which one to use.

The solution is to add the module name like this `ThirdPartyModule.Product` to the parameter but as this code is auto-generated I don't know how to do it.

Any ideas? Thank you!

**Comment by amichnia** [comment]
@pballart Try using Swifty Mocky 3.2-pre

Thanks for raising, I also recently noticed this issue. Sorry for inconvenience, naming it Product was not the best idea ever 😅

**Comment by pballart** [comment]
@amichnia version 3.2-pre works fine 🎉 
Thank you!
