### ISSUE TITLE
Build error with XCode 10.1 (10B61)

### ISSUE THREAD

**Issue by Beniamiiin** [MakeAWishFoundation/SwiftyMocky#179]
XCode gives compile time error when built with SwiftyMocky. Project on Swift 4.2.

<img width="1408" alt="Screenshot 2019-03-28 at 14 30 42" src="https://user-images.githubusercontent.com/4854239/55154615-4c4adf00-5166-11e9-9036-4126d42145bb.png">

`case m_setRemoteConfig__config(Parameter<[String: String]>)`

**Comment by Beniamiiin** [comment]
It works with `pod 'SwiftyMocky', '~> 3.2.0-pre'`.

**Comment by amichnia** [comment]
@Beniamiiin Good to hear. Final 3.2 is on its way, we will also address some issues with Xcode 10. I consider this issue handled then :)
