### ISSUE TITLE
Build error with Xcode Version 10.2 (10E125)

### ISSUE THREAD

**Issue by fandor92** [MakeAWishFoundation/SwiftyMocky#180]
After upgrading to Xcode 10.2, i get "SWIFT_VERSION '3.1' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'SwiftyMocky')" error when compiling. When i try to manually change the swift version of the pod target, i get several other compile errors.

**Comment by draperj** [comment]
Same here as well.

**Comment by amichnia** [comment]
@draperj @fandor92  Hi guys - I will look into that. Could you try first with pre-release version? it would be `pod 'SwiftyMocky', '~> 3.2.0-pre'`

**Comment by fandor92** [comment]
Hey, thank you for your quick response. Already tried, did not solve the problem.

**Comment by draperj** [comment]
This resolved it for me, I can also set the SwiftyMocky pod version in the "Pod" project to Swift 4 to resolve the issue. I am now experiencing the below when running:
Pods/Sourcery/bin/sourcery --config mocky.yml

Error:

> error: /var/folders/lv/203xycw979sc66tp3xk19sph0000gn/T/SwiftTemplate.build/main.swift:2:8: error: module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler: /var/folders/lv/203xycw979sc66tp3xk19sph0000gn/T/SourceryRuntime.framework/Modules/SourceryRuntime.swiftmodule/x86_64.swiftmodule
> import SourceryRuntime

**Comment by draperj** [comment]
> This resolved it for me, I can also set the SwiftyMocky SWIFT_VERSION in the "Pod" project to Swift 4 to resolve the issue

Looking into this further, using 3.1.1 and changing the SWIFT_VERSION worked. Switching to 3.2.0-pre caused me the issues OP described.

**Comment by Rag0n** [comment]
Hi! The version 3.2.0-pre doesn't solve issue for me as well.
`error: Error Domain=NSCocoaErrorDomain Code=4 "“SwiftTemplate” couldn’t be moved to “Mock.swifttemplate” because either the former doesn’t exist, or the folder containing the latter doesn’t exist."`

**Comment by mpdifran** [comment]
Anything I can do to help get version `3.2.0-pre` working?

**Comment by amichnia** [comment]
@mpdifran  I will look into it. I allocated time for that for today and tomorrow. In the meantime - as a workaround you can check, Sourcery should be also available via brew I think. Or they can have working binary, this wan is a bit outdated

**Comment by amichnia** [comment]
@Rag0n @mpdifran @draperj I'm working on fully migrating to Swift 4+. As for the generation itself, I found that removing Sourcery cache was enough. I did `~/Library/Caches/Sourcery` and I am still able to use Sourcery obtained with "get_sourcery" script. 

Still, there are some changes I need to address, stay tuned.

**Comment by amichnia** [comment]
@Rag0n @mpdifran @draperj @fandor92 SwiftyMocky 3.2 is released. Should work now properly with Xcode 10.2

**Comment by fandor92** [comment]
I can confirm that after clearing Sourcery cache and updating pod to 3.2.0, warnings and errors are gone. Thanks for the great support!

**Comment by mpdifran** [comment]
Thanks for the quick turnaround!
