### ISSUE TITLE
Swift 5 @autoclosure forwarding ban

### ISSUE THREAD

**Issue by fuzza** [MakeAWishFoundation/SwiftyMocky#187]
## Description

Prior to Swift 5, it was possible to forward `@autoclosure` function parameter to another function as following:

```swift
func func(_ param: @autoclosure () -> String) {
  anotherFunc(param)
}

func anotherFunc(_ param: @autoclosure () -> String) {
  //...
}
```

In Swift 5 this behavior was considered as  a [bug](https://bugs.swift.org/browse/SR-5719) and fixed. 

In context of the SwiftyMocky framework, this causes mocks for protocols that define methods with autoclosure params to be generated with an error:

```swift
protocol Connector {
  func connect(_ token: @autoclosure () -> String)
}
```

Mock implementation in 
```swift

open class ConnectorMock: Connector, Mock {
 
  open func connect(_ token: @autoclosure () -> String) {
    addInvocation(.m_connect__token(Parameter<() -> String>.any))
    let perform = methodPerformValue(.m_connect__token(Parameter<() -> String>.any)) as? (@autoclosure () -> String) -> Void
    perform?(`token`) // Add () to forward @autoclosure parameter
    }
```

## Environment

* Xcode 10.2
* Swift 5
* CocoaPods 1.6.0
* SwiftyMocky 3.2.0 integrate

I would appreciate any feedback from contributors on this issue. Thanks in advance!

**Comment by amichnia** [comment]
Done, will be part of 3.3 release
