### ISSUE TITLE
[new feature] Mocking Models

### ISSUE THREAD

**Issue by laxmorek** [MakeAWishFoundation/SwiftyMocky#196]
Hey,

A few days ago I upgraded SwiftyMocky in my project to the newest version because in our company we found time ( :O ) to write some unit tests in current projects. During work I realized that something is missing in SwiftyMocky.

Mocking (stubbing) Models.

**Example.**

```swift
// model
struct User {
   let name: String
   let age: Int
}

// function to test
func filterUsersOfAge(_ users: [User]) -> User {
    return users.filter { $0.age >= 18 }
}
```

_Testing now:_
```swift
let users = [
   User(name: "Xyz", age: 8),
   User(name: "Qwerty", age: 21)
]

let result = filterUsersOfAge(users)
XCTAssertEqual(result, 1)
```

_Idea:_
We can add new Sourcery template which can generate additional function for every model marked by us. This new function will provide mocked models
```swift
//sourcery: AutoMockableModel
struct User {
   let name: String
   let age: Int
}

// testing
let mockedUsers = User.generateStubs(count: 3)
```

For now it is just an idea. We can think about it and discuss. I can see a lot of possibilities here.

_We can consider:_
1. Using Sourcery annotations to add constrains:
```swift
//sourcery: AutoMockableModel
struct User {
   let name: String
   /// sourcery: mocky_max = 5
   let age: Int
}
```
2. Many types of generated functions:
```swift
let mockedUsers = User.generateStubs(count: 3, defaultName: "qwerty")
let mockedUsers = User.generateStubs(count: 4, age: .moreThan(3))
```

What do you think? :)

**Comment by Przemyslaw-Wosko** [comment]
I don't think this is functionality we want to make and support in SwiftyMocky, but this kind of stuff sure might be helpfull for some cases, so maybe new library would be a good choice? 
@andrzejmichnia  what do you think?

**Comment by amichnia** [comment]
@laxmorek It seems to be a nice feature, but I have some doubts. I don't want to extend SM. too much. I was thinking about subspec, but then it means problems for Carthage, which will require separate library.

I still believe it should be a part of SwiftyMocky suite, but probably, as @Przemyslaw-Wosko said, a bit separate in the same time. 

I would definitely give it a try, then we can decide whether it goes to main framework, or does it deserve separate one.

From the challenges I see:
1. Supporting structs 
2. Supporting classes
3. Custom init's
4. Defining default values

**Comment by laxmorek** [comment]
@Przemyslaw-Wosko @amichnia thanks for the quick response.

Separate library sounds good to me. Maybe as a part of MakeAWishFoundation? 

I agree that challenges are many and I don't have ideas how to achieve all of them for now. This feature is just an idea which I would like to discuss. But.. we can start with something small and easy and after that expand it. :) 

Both of you agreed that it should not be a part of SwiftyMocky so I am closing this issue :)

**Comment by amichnia** [comment]
@laxmorek Feel free to start working on it, I will prepare separate container for it

**Comment by laxmorek** [comment]
@amichnia tnx
