### ISSUE TITLE
Random ShellOut error when running `swiftymocky generate`

### ISSUE THREAD

**Issue by DavidHorvath** [MakeAWishFoundation/SwiftyMocky#199]
Hi,

I get this error randomly when I run `swiftymocky generate` so my CI job fails. 
Have you ever seen this error? Is there something I could do with it?

```
❌  Error: ShellOut encountered an error
Status code: 3
Message: "sourcekit: [1:connection-event-handler:11779: 0.0000] Connection interruptsourcekit: [1:updateSemanticEditorDelay:11779: 0.0004] disabling semantic editor for 10 secondssourcekit: [1:pingService:11779: 0.0004] pinging servicesourcekit: [1:sourcekitd_send_request_sync:7683: 0.0013] request dropped while restoring servicesourcekit: [1:sourcekitd_send_request_sync:9219: 0.0025] request dropped while restoring servicesourcekit: [1:sourcekitd_send_request_sync:7939: 0.0031] request dropped while restoring servicesourcekit: [1:sourcekitd_send_request_sync:8963: 0.0031] request dropped while restoring servicesourcekit: [1:sourcekitd_send_request_sync:9483: 0.0041] request dropped while restoring servicesourcekit: [1:ping-event-handler:11779: 0.0083] service restoredrestoring service"
Output: "🌱  Sourcery 0.16.1 already installed
🌱  Running sourcery 0.16.1...
Using configuration file at '<path_to_my_project>/.mocky/.config.yml.tmp'
Scanning sources...
error: restoring service"
```

Thanks in advance

**Comment by amichnia** [comment]
Hi @DavidHorvath 

I have not encountered that, seems bizarre. I understand you actually stripped output a bit, so `<path_to_my_project>/.mocky/.config.yml.tmp` is actually a correct path, right?

I have some questions/workarounds you might try until we figure it out:

1. Can you check if adding `--disableCache` helps?
2. Is it required to generate mocks on the CI? I'm curious about the use case. I mean it makes sense in our situation, as our CI tests generation process, but in most development cases you only run tests on CI, and the dev is responsible to make them work (including re-generating mocks)
3. What swift toolchain do you use? 
4. What does it mean randomly? Does it mean that retrying job actually helps? Or is it persistent?

Anyway, it seems it is SourceKit crashing, which might not be something we can really help. I've seen some open radars and issues from 2015-2016, but nothing really recent here.

**Comment by amichnia** [comment]
I have not encountered it for a moment, we also updated the version of ShellOut in v3.4.0, so I consider it closed for now. Feel free to reopen if it keeps showing up in the upcoming version 3.4.0.

**Comment by im4nkur** [comment]
I am facing the same issue. Any help would be appreciated. 
I have tried:
  i) Updating Sourcery Version to 0.18.0.
  ii) Reinstalling SwiftyMocky
  iii) SwiftyMocky doctor returns all green.

Nothing worked for me. Is there anything I need to install? 

`❌  Error: ShellOut encountered an error
Status code: 1
Message: "Unknown Arguments: <path_to_project>/.mocky/.config.yml.tmp

Options:
    --watch [default: false] - Watch template for changes and regenerate as needed.
    --disableCache [default: false] - Stops using cache.
    --verbose [default: false] - Turn on verbose logging
    --quiet [default: false] - Turn off any logging, only emmit errors.
    --prune [default: false] - Remove empty generated files
    --sources - Path to a source swift files. File or Directory.
    --exclude-sources - Path to a source swift files to exclude. File or Directory.
    --templates - Path to templates. File or Directory.
    --exclude-templates - Path to templates to exclude. File or Directory.
    --output - Path to output. File or Directory. Default is current path.
    --config - Path to config file. File or Directory. Default is current path.
    --force-parse - File extensions that Sourcery will be forced to parse, even if they were generated by Sourcery.
    --args - Custom values to pass to templates.
    --ejsPath - Path to EJS file for JavaScript templates."
Output: ""`
