### ISSUE TITLE
Use of unresolved identifier 'MockyAssert' in generated Mock file

### ISSUE THREAD

**Issue by jimidriscoll** [MakeAWishFoundation/SwiftyMocky#200]
When building my test target (after adding SwiftyMocky to my test target in my Podfile and having run 'Pod Install'), I get a "Use of unresolved identifier 'MockyAssert'" error in my generated Mock file. I find this odd considering the mock file does indeed include  'import SwiftyMocky' at the top. Am I missing a step somewhere?

**Comment by amichnia** [comment]
@jimidriscoll Hello. From the 3.3.2, the MockyAssert was moved to the runtime library. Previously it was part of generated mock.

Could you please share the top of the generated file? Also, you can run pod update to make sure your runtime is 3.3.2 (or check on Podfile.resolved)

**Comment by jimidriscoll** [comment]
Indeed, it had to do with my version. After a _pod repo update_ and a _pod update_ I noticed the immediate upgrade to 3.3.2. Builds fine now. Thanks for pointing me in the right direction, I completely forgot to double check the version number!
