### ISSUE TITLE
SwiftyMocky 3.3.2 not compiling under Xcode 10.2.1

### ISSUE THREAD

**Issue by pgorzelany** [MakeAWishFoundation/SwiftyMocky#201]
I am surprised nobody mentioned this issue before. Makes me wonder if its an error with the setup on my side.

Anyway, I integrated SwiftyMocky 3.3.2 with Cocoapods into a Swift 5 project. I tried to compile the test target under Xcode 10.2.1 and got the following compilation error in CustomAssertions.swift

<img width="915" alt="Screenshot 2019-06-23 at 15 04 53" src="https://user-images.githubusercontent.com/3740966/59976684-4a0eea00-95c8-11e9-9246-6eedbdf98559.png">

Is this a known issue? Any idea how can I workaround it?

Thanks for the help!

**Comment by amichnia** [comment]
@pgorzelany I will send an update. I don't know how did it passed tests, we already fixed it for wacky assert, this one we must have missed.

**Comment by amichnia** [comment]
@pgorzelany You can check SwiftyMocky 3.3.3, the fix should be already there

**Comment by amichnia** [comment]
OK, no info about any more problems, closing.

**Comment by pgorzelany** [comment]
@amichnia sorry, didn't have time to check. I just integrated SwiftyMocky 3.3.3 and no compilation errors are present. Thanks for your swift response and fix :)
