### ISSUE TITLE
[FATAL] No registered matcher comparator for (key: String, value: Any)

### ISSUE THREAD

**Issue by bishalpatnaik-nineleaps** [MakeAWishFoundation/SwiftyMocky#202]
How do I register a matcher for 
[String: Any] type variable

**Comment by amichnia** [comment]
@bishalpatnaik-nineleaps Hi, you can check documentation here: [Matcher docs](https://cdn.rawgit.com/MakeAWishFoundation/SwiftyMocky/3.3.3/docs/matcher-support-for-not-equatable.html)

But to make it easier, the general rule seems as following:

```swift
Matcher.default.register([String: Any].self) { (lhs, rhs) -> Bool in
            // Do the custom matching here, and return true if same and false otherwise
            return true or false, depending if they are "same"
        }
```

The biggest question is how do you actually plan to compare two [String: Any] instances. Also, please remember that Matcher needs to be setup before test, and that Matcher.default is a shared singleton.

**Comment by bishalpatnaik-nineleaps** [comment]
Thanks for the reply, this is the function I wrote in the  override func setup() function of my test class

Matcher.default.register([String : Any].self) { (lhs, rhs) -> Bool in
            return NSDictionary(dictionary: lhs).isEqual(to: rhs)
        }

NSDictionary(dictionary: lhs).isEqual(to: rhs)  returns true if same and false otherwise. But still, it says
[FATAL] No registered matcher comparator for (key: String, value: Any)

Any ideas why this is happening.

**Comment by nrichards** [comment]
Use `AnyObject`

```
Matcher.default.register([String: AnyObject].self) { (lhs, rhs) -> Bool in
    NSDictionary(dictionary: lhs).isEqual(to: rhs)
}
```

**Comment by AhmadFayyas** [comment]
In my case, I was able to resolve it by registering it as a `(key: String, value: Any).self` instead of `[String: Any].self`.
The element of the dictionary is a tuple as if `(key: value:)`.

**Comment by InderKumarRathore** [comment]
The Element of Dictionary is `(key:, value:)` so we need to register the Element which is Tuple in case of Dictionary.
```
        Matcher.default.register((key: String, value: Any).self) { (lhs, rhs) -> Bool in
            guard let lhsValue = lhs.value as? String,
                  let rhsValue = rhs.value as? String else {
                return false
            }
            return lhsValue == rhsValue && lhs.key == rhs.key
        }
```

This is because of 
```
public extension Parameter where ValueType: Sequence {
    /// Element
    typealias Element = ValueType.Element
```
