### ISSUE TITLE
Fatal error while registering [String: Any] types. 

### ISSUE THREAD

**Issue by nischith-nineleaps** [MakeAWishFoundation/SwiftyMocky#203]
Matcher.default.register([String : Any].self) { (lhs, rhs) -> Bool in
return NSDictionary(dictionary: lhs).isEqual(to: rhs)
}

NSDictionary(dictionary: lhs).isEqual(to: rhs) returns true if same and false otherwise. 
But still, it says:
[FATAL] No registered matcher comparator for (key: String, value: Any)

Any ideas why this is happening

**Comment by amichnia** [comment]
@nischith-nineleaps What version of Swift are you using? I have added tests for that and it seems it seems to work, so probably we missed some particular setup which fails.

**Comment by amichnia** [comment]
@nischith-nineleaps  I believe this was fixed in 3.3.4, please reopen if it happens again.
