### ISSUE TITLE
Need clear verify

### ISSUE THREAD

**Issue by shingo-nakanishi** [MakeAWishFoundation/SwiftyMocky#210]
I want a mechanism to clear `verify`.
The mockito seems to have multiple mechanisms to reset the `verify`.

I think we should delete the corresponding part from the array in the mock.
`private var invocations: [MethodType]`

**Comment by amichnia** [comment]
@shingo-nakanishi working on that

**Comment by shingo-nakanishi** [comment]
@amichnia Thank you. I can't wait for completion.

**Comment by amichnia** [comment]
@shingo-nakanishi I planned release for this week. The method would look like that:

```swift
mock.clear() // clear all
mock.clear(.invocations) // only verify is cleaned, rest stays
mock.clear(A...) //  where A  subset of {invocations, given, perform} 
```

**Comment by shingo-nakanishi** [comment]
@amichnia

Thank you. 

My colleague's Android engineer says this is a `reset` method in the `Mockito`.
And `SwiftyMocky` README say

```
SwiftyMocky is Lightweight, strongly typed framework for Mockito-like unit testing experience.
```

So my colleague's Android engineer say

```
mock.reset()
mock.reset(.invocations)
mock.reset(A...)
```

is better then `clear`.
I want you to make the final decision on which method name to use.

**Comment by amichnia** [comment]
@shingo-nakanishi makes sense for me. There was already clear method for StaticMocks (to cleanup static methods givens and invocations), so I'll just deprecate it. Thanks for the tip!

**Comment by shingo-nakanishi** [comment]
@amichnia Thank you for making `resetMock`.
