### ISSUE TITLE
Getting unspecified error

### ISSUE THREAD

**Issue by francoguerrerog** [MakeAWishFoundation/SwiftyMocky#211]
Hello, every time I run `Pods/Sourcery/bin/sourcery --config LocalPods/Login/mocky.yml` on my Mac I get error but it doesn't specify it.

`Using configuration file at 'LocalPods/Login/mocky.yml'
Scanning sources...
	loadOrParse: 0.028198957443237305
	resolution took 0.0034279823303222656
	combiningTypes: 0.006945013999938965
	total: 0.035902976989746094
Found 14 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.01948392391204834
Generating code...
error:`

It only happens on my Mac, when I try on others Macs it goes well

**Comment by amichnia** [comment]
Hi @francoguerrerog ,  have you tried cleaning up sourcery cache?

I would suggest running it once with `--disableCache` flag

**Comment by amichnia** [comment]
@francoguerrerog I assume for now it was Sourcery cache problem (had same error recently). If it still happens after upgrading all to SM 3.4.0 and running with `--disableCache`, feel free to reopen it.
