### ISSUE TITLE
Custom templates with swiftymocky CLI?

### ISSUE THREAD

**Issue by mikeakers** [MakeAWishFoundation/SwiftyMocky#214]
Hello, In our project we have modified the sourcery templates to make the `matchingCalls() -> Int` method public, and add a method to clear the `invocations` array. I tried updating to the latest Swiftymocky and the CLI but it seems that using custom templates is no longer supported. Is this true? Is there a supported way to achieve the same functionality with the CLI?

Thanks in advance, Mike

**Comment by amichnia** [comment]
@mikeakers working on this. I will make clear methods in our template.

As for custom templates, they are still possible, but they are not a part of CLI. If you want to generate custom templates alongside SwiftyMocky, feel free to follow Sourcery documentation, or check our "legacy" section in documentation.

**Comment by amichnia** [comment]
@mikeakers clear would be done in #210 

As for custom templates, I think I would add a setting in Mockfile, but I need a bit more checks on that.

**Comment by amichnia** [comment]
Added new 'sourcery' entry to Mockfile, allowing to specify paths to additional Sourcery configurations, that would be executed alongside Mock generation
