### ISSUE TITLE
Failing cast in ExpressibleByArrayLiteral extension

### ISSUE THREAD

**Issue by chuckluck44** [MakeAWishFoundation/SwiftyMocky#223]
This is from the Parameter+Literals.swift file:

```swift
private extension ExpressibleByArrayLiteral {
    init(_ elements: [ArrayLiteralElement]) {
        self = elements as! Self  // TODO: Check if can be fixed. For some reason could not use init(arayLiteral elements: ...)
    }
}

extension Optional: ExpressibleByArrayLiteral where Wrapped: ExpressibleByArrayLiteral {
    public typealias ArrayLiteralElement = Wrapped.ArrayLiteralElement

    public init(arrayLiteral elements: ArrayLiteralElement...) {
        self = .some(Wrapped.init(elements))
    }
}
```

Our unit tests are crashing on the line marked with a TODO. We have multiple instances where we assign an array literal to an optional `Set` var.
```swift
var optionalSet: Set<Int>? =  [0, 1, 2]
```
In this case `self = elements as! Self` will fail because elements ([0, 1, 2]) is an Array type and can't be cast to Self which is a `Set` type.

This is going to fail for anything that implements ExpressibleByArrayLiteral that is not an Array.

**Comment by chuckluck44** [comment]
Did some more digging on this, and found that array splatting isn't supported in Swift yet: https://bugs.swift.org/browse/SR-128. A common work around is to cast the variadic function to a closure that accepts an array.

**Comment by amichnia** [comment]
@chuckluck44 Thanks! I was going to release 3.4.0 today, I'll try to include a fix. 

What Swift version are you using?

**Comment by amichnia** [comment]
@chuckluck44 FYI, I had to change it a bit since for some reason it was still failing when trying to initialise set with an array. Seems that constraining `ArrayLiteralElement` to `Hashable` helped. This is final solution:

```swift
// MARK: - ExpressibleByArrayLiteral
private extension ExpressibleByArrayLiteral {
    init(_ elements: [ArrayLiteralElement]) {
        let castedInit = unsafeBitCast(Self.init(arrayLiteral:), to: (([ArrayLiteralElement]) -> Self).self)
        self = castedInit(elements)  // TODO: Update once splatting is supported. https://bugs.swift.org/browse/SR-128
    }
}

private extension ExpressibleByArrayLiteral where ArrayLiteralElement: Hashable {
    init(_ elements: [ArrayLiteralElement]) {
        let castedInit = unsafeBitCast(Self.init(arrayLiteral:), to: (([ArrayLiteralElement]) -> Self).self)
        self = castedInit(elements)  // TODO: Update once splatting is supported. https://bugs.swift.org/browse/SR-128
    }
}
```

**Comment by chuckluck44** [comment]
Great thanks @amichnia !
