### ISSUE TITLE
SwiftUI previews do not work when using SwiftyMocky

### ISSUE THREAD

**Issue by MohammadAG** [MakeAWishFoundation/SwiftyMocky#225]
When building SwiftUI previews, the build fails due to:

Mock.generated.swift:396:12: Type 'ClassNameMock' does not conform to protocol 'Mock'

Normal builds are fine, disabling tests completely also fixes SwiftUI previews. Not sure why Xcode is building tests when previewing SwiftUI anyway.

**Comment by dchohfi** [comment]
Hey @MohammadAG , I think you need to bump the CLI tool to 3.4.0

**Comment by MohammadAG** [comment]
That was it, thanks! I assumed I'd installed it through brew since I always keep that up to date, guess I was wrong.
Thanks again!
