### ISSUE TITLE
does not conform to protocol 'Mock' in 3.4.0

### ISSUE THREAD

**Issue by shingo-nakanishi** [MakeAWishFoundation/SwiftyMocky#226]
## I try

```
> swiftymocky setup
   > Please choose one of possible actions: (Yes, No)
   Y
   > Please choose one of possible actions: (1, Override all, Cancel)
   1
> swiftymocky generate
```

## Error in generated file.
> does not conform to protocol 'Mock'
> Do you want to add protocol stubs?

## click the error, Xcode add the code

```
    public func resetMock(_ scopes: MockScope...) {
        <#code#>
    }
```

**Comment by shingo-nakanishi** [comment]
Self resolve.

I found

```
swiftymocky generate
╔════════════════════════╗
║ SwiftyMocky CLI v3.3.3 ║
╚════════════════════════╝
```

this mean cli version still v3.3.3.

so more try

```
mint install MakeAWishFoundation/SwiftyMocky 
```

then

swiftymocky setup show
╔════════════════════════╗
║ SwiftyMocky CLI v3.4.0 ║
╚════════════════════════╝

**Comment by amichnia** [comment]
OK, great to hear it works.
