### ISSUE TITLE
Use generated mocks files in other projects

### ISSUE THREAD

**Issue by remkoseelig** [MakeAWishFoundation/SwiftyMocky#228]
**Introduction**
First of all, I'm relatively new to SwiftyMocky and my main experience with mocking is using Moq in a C# environment. Although I am very impressed by SwiftyMocky, I am looking for an edge case that I cannot, or don't know how to, resolve with SwiftyMocky.

**Generating mocks from (external) libraries**
I'm working on a few libraries/frameworks that are dependent on each other and thus I require to generate mocks. Sometimes I require mocked classes that are defined in other projects/libraries/frameworks. This is where my problem lies, I don't know how to properly manage this.

1) It looks like SwiftyMocky only generates mock classes for files annotated in the current project. If I need to mock classes from other projects, I cannot annotate them. Extending those classes and annotating them does not help because it appears SwiftyMocky then only mocks the extension code. The only solution I see is (re)creating a protocol definition for the class to be mocked, annotate it and use it in my test code. 
- It's actually not a bad practise because as it requires to explicitly extend the actual class to conform to my protocol, when this external class has changed the compiler detects protocol non-conformity. This is - I guess - the way you should mock Apple or 3rd party classes?
- When I am in control of the classes myself, this is a bit boilerplate, as I already created the classes in my source library.

2) When creating classes in my source library, I normally provide them with a Protocol as well so my classes are dependent to the protocol instead of concrete implementation (SOLID, anyone?). This means I -could- generate the mocks here is well. I came up with the idea to generate two libs/frameworks, one with my concrete classes, and one with the generated mocks. This way, the mocked code is in a separate library, and my unit test class header looks like:

```
import XCTest
import TestLib
import TestLibMocks

class TestLibTests: XCTestCase {
```

The only problem here is that the generated classes by SwiftyMocky are open classes, and all protocol functions are public, except for the initializer, which are internal. The test code below does not compile because the initialiser is internal:

```
    func testMock() { 
        let mock = TestLibProtocolMock()  
    }
```

I resolved this by a post build/mock script where I replace the `init(...)` with `public init(...)`:

```
# Type a script or drag a script file from your workspace to insert its path.
swiftymocky generate
sed -i '' "s/\ \ \ \ init/\ \ \ \ public\ init/g"
```

I don't know if this is the way to go, so I am looking for some anchors here:
- What would be the recommended way to mock with Swift? Should I generate and supply mocks with my library, or should the code that requires the mocks create the protocol code for mocking, even when this leads to a bit boilerplate?
- Is this idea of generating and providing mock classes with your lib/framework a good idea anyway, and would it be a good feature anyway to generate public init for mocks (in that case, this issue can be considered a change request)

**Comment by amichnia** [comment]
@remkoseelig Hi, thank you for the long and detailed description. Actually, these are very good questions. We are struggling with a similar problem with our SDK's suite now.

I would like to prepare a detailed answer, so I just need to recheck how we approach that. I will try to write something more exhaustive this week. 

For now, I can tell, that:
1. we used @testable to import our "Mocks" library shipped with SDKs. 
2. Another big problem was actually not due to SiwftyMocky, but we had a lot of data models, passed here and there, that have private initializers.
3. Ambiguity for some data models - we had custom `Request` model, that "clashed" with `Request`. from Alamofire. There is a new `typealias` kind-of-annotation from SwiftyMocky 3.4.0, you can use to to resolve these kinds of issues.

**Comment by remkoseelig** [comment]
Cool! Thanks for elaborating on this, @amichnia.

@testable indeed is a way to import those mocks, exactly like you'd do for the existing code you want to test so that of course would be a major improvement to my 'sed' hack.

Still, I'd be interested in the other things you're referring to.

With respect to this GitHub project, would it be an idea to document some of these practices you propose? Reflecting on my experience as a new SwiftyMocky user, it would help if the basic documentation would contain something like this and maybe also link to this documentation page from the README.

**Comment by g-amichnia** [comment]
Done in 4.0.0

**Comment by remkoseelig** [comment]
Nice! Going to take a look at it soon!
