### ISSUE TITLE
Mock for protocol/method with `@available` attribute isn't generated correctly. 

### ISSUE THREAD

**Issue by spaluchiewicz** [MakeAWishFoundation/SwiftyMocky#230]
Mocks generated for protocols:

```
//sourcery: AutoMockable
@available(iOS 14, *) protocol ProtocolA {
    func funcA()
}

//sourcery: AutoMockable
protocol ProtocolB {
    @available(iOS 14, *)
    func funcB(_ dependency: ProtocolA)
}
```
aren't surrounded with correct @available attributes

```
...
// MARK: - ProtocolA
open class ProtocolAMock: ProtocolA, Mock {
...
open func funcB(_ dependency: ProtocolA) {
```

which causes compilation error:
```
... 'ProtocolA' is only available in iOS 14 or newer
```
![SwiftyMocky_available_issue](https://user-images.githubusercontent.com/782101/70320599-6ffe1300-1825-11ea-92eb-3289b65a9e46.png)

Note: iOS 14 is used here only as an example.

**Comment by mpdifran** [comment]
+1 for this. Is there a timeline for when Version 4 will ship?

**Comment by Przemyslaw-Wosko** [comment]
Hi, i'm not sure if i will have time in this month, have you thought about contributing?

**Comment by mpdifran** [comment]
I'll try and take a look at implementing sometime this week.

**Comment by g-amichnia** [comment]
Done for 4.0.0
