### ISSUE TITLE
How to use SwiftMocky when my unit test code is in Pods.

### ISSUE THREAD

**Issue by DaolangHuang-TW** [MakeAWishFoundation/SwiftyMocky#232]
There is no Unit Test target in my App, and the Test code is in separate Pods. The way I use Pods is {pod 'MyPods', :testspecs => [' Test']}, so he can automatically run my Test code.
When I use: Swiftymocky setup, prompt "Specified project was not found!" .
I hope to get your help.

**Comment by amichnia** [comment]
@DaolangHuang-TW hello, I have never tried to do it that way, I need to check. I do believe you need to call `swiftymocky setup` (you wanted to generate mocks with CLI, right?) from the right directory, or call it with path argument, like:

```bash
swiftymocky setup path/to/project.xcodeproj
```

**Comment by g-amichnia** [comment]
OK, seems to be either fixed or not relevant anymore.
