### ISSUE TITLE
Not able to install Swift Package 3.5.0

### ISSUE THREAD

**Issue by vincefried** [MakeAWishFoundation/SwiftyMocky#238]
I am currently not able to install the Swift Package due to the error "Product 'Crayon' not found. It is required by target 'SwiftyMockyCLICore'.". When checking the dependencies in the Swift.Package I saw that it now points to https://github.com/luoxiu/Chalk instead of https://github.com/jianstm/Crayon and also the version updated, maybe there's a problem.

**Comment by fevicks** [comment]
Me too having the same issue, it was woking fine before few days, now not working

**Comment by KKirsten** [comment]
Created #241 to fix this issue

**Comment by Przemyslaw-Wosko** [comment]
@KKirsten thanks for work! PR merged, should solve issue
