### ISSUE TITLE
Issue while adding package - Version 3.5.0

### ISSUE THREAD

**Issue by fevicks** [MakeAWishFoundation/SwiftyMocky#239]
I am getting below issue while adding package in xcode 11.3.1

<img width="727" alt="Screen Shot 2020-03-16 at 1 03 19 PM" src="https://user-images.githubusercontent.com/1110539/76745651-4ee38180-6787-11ea-9486-250c5f284e20.png">

**Comment by KKirsten** [comment]
Created #241 to fix this issue

**Comment by Przemyslaw-Wosko** [comment]
Duplicate od #238 ? since its closed, i'm also closing this one. You can always reopen issue / rise new one
