### ISSUE TITLE
swiftymocky setup then it was saying:Cloning Sourcery 0.17.0 and get stuck forever

### ISSUE THREAD

**Issue by tickboxs** [MakeAWishFoundation/SwiftyMocky#243]
please help me with this:

1. Initializing new Mockfile™ at /Users/charliecai/Desktop/job_seek/fujiko/fujiko
✅  Found 1 unit test bundles:
  ☑️  1) fujikoTests 
fujikoTests - adding Mock configuration...
 -> Targets set to: fujikoTests
 -> Default output set to: ./fujikoTests/Mock.generated.swift
 -> Default sources directory: ./fujiko
 -> Default testable module: fujiko
 -> Default testable module: Foundation
🌱 Cloning Sourcery 0.17.0

Here I waited for 15 mins then I got error below:

❌  Error: ShellOut encountered an error
Status code: 1
Message: "Cloning into 'github.com_krzysztofzablocki_Sourcery'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
🌱 Encountered error during "git clone --depth 1 -b 0.17.0 https://github.com/krzysztofzablocki/Sourcery.git github.com_krzysztofzablocki_Sourcery". Use --verbose to see full output
🌱  Couldn't clone https://github.com/krzysztofzablocki/Sourcery.git 0.17.0"
Output: "🌱 Cloning Sourcery 0.17.0"

**Comment by vincefried** [comment]
Having the same problem

**Comment by g-amichnia** [comment]
Ok, I finally have some time to look into that. Not sure if we can do much about it though if I cannot reproduce the problem.

@tickboxs @vincefried Could you give me some more info? Does it happen every time? Do you use Mac or linux?

**Comment by g-amichnia** [comment]
OK, it might be one time issue, or some git configuration issue. 

https://stackoverflow.com/questions/24952683/git-push-error-rpc-failed-result-56-http-code-200-fatal-the-remote-end-hun/36843260#36843260
