### ISSUE TITLE
Cocoapods - SwiftyMocky 3.6

### ISSUE THREAD

**Issue by xploit42** [MakeAWishFoundation/SwiftyMocky#247]
Hello, I was wondering why the release 3.6 isn't available on cocoapods, is there any reason?

Thank you

**Comment by amichnia** [comment]
Good question. If I have to guess, I'd say that's because we are forced to match CLI version with library itself, due to this one-repo setup (which is insufficient). That said, I think 3.6 was only CLI changes, that's why pods got skipped. If no, I will see and release it.

**Comment by g-amichnia** [comment]
There is new release coming, I think I can close this for now. We are probably moving towards splitting repos and moving CLI to new repo, so we can track that separately.
