### ISSUE TITLE
SPM - Chalk resolves to 0.07

### ISSUE THREAD

**Issue by ohitsdaniel** [MakeAWishFoundation/SwiftyMocky#248]
Hi there, 

I tried to integrate the SwiftyMockyCLI via SPM into our setup and wanted to use `swift run swiftymocky generate` as part of a run script phase. To do so, I set up a `Package.swift` file that only lists the SwiftyMocky package in its dependencies. However, when trying to build the executable, `swift build` / `swift run` fails as Chalk resolves to `0.0.7` instead of `0.0.4` and there were breaking changes in `TerminalString`.

Creating a fresh SPM package and adding SwiftyMocky as a depedency results in the following `Package.resolved` file:
```json
{
  "object": {
    "pins": [
      ...
      {
        "package": "Chalk",
        "repositoryURL": "https://github.com/luoxiu/Chalk",
        "state": {
          "branch": null,
          "revision": "fbb0adbe8a54d8dbfcb4824ebc96bd3b401d0757",
          "version": "0.0.7"
        }
      },
      ...
    ]
  ...
}
```

I attached a sample project:
[Example.zip](https://github.com/MakeAWishFoundation/SwiftyMocky/files/4609764/Example.zip)

There are two ways to solve this:
1. Pin the Chalk dependency version to `0.0.4`
2. Update the chalk dependency to 0.0.7 and fix the build error.

I forked off and will open a PR that follows the second approach as the build errors are rather easy to solve. It will also pin the version to `0.0.7` so that this will not happen again in the future.

**Comment by g-amichnia** [comment]
PR is merged now, I will test it and start preparing new release. I will close it for now.
