### ISSUE TITLE
Some Mock.generated files.

### ISSUE THREAD

**Issue by StasanTelnov** [MakeAWishFoundation/SwiftyMocky#250]
Hello.
At now, all generated mocks writed to one file: `Mock.generated.swift`
How I can generate multiple mock files? Maybe I can edit sourcery template?

All mocks in one file is not comfortable, file becomes very large.

I would like, that mocks repeats original strucure. For example, if I have AutoMockable protocol in file `MyTarget/Modules/MyModule/MyProtocol.swift`. After generate I want see `UnitTests/Modules/MyModule/MyProtocolMock.generated.swift` file.

It is possible in current SwiftyMocky 3.5.0 version?

**Comment by Przemyslaw-Wosko** [comment]
@StasanTelnov i think there was a way at very beginning, but we didn't support that feature cause of locks on files and that generation process was a way more error prone, than handling just one file.

**Comment by g-amichnia** [comment]
@StasanTelnov It is possible. It is not default, and there is no CLI feature for that, but feel free to look into our [Mockfile](https://github.com/MakeAWishFoundation/SwiftyMocky/blob/master/Mockfile) to see how to do it.

In general - every section is separate Mock.generated.swift file. You can change output names if you want to have several generated files under same target.
