### ISSUE TITLE
Can't use SwiftyMocky for both prototyping and mocking

### ISSUE THREAD

**Issue by maxxx777** [MakeAWishFoundation/SwiftyMocky#251]
Hello,
In my custom pod I wanna use `SwiftyMocky` for both 
- mocking in the pod tests
- prototyping in the example app of the pod

`MyPod.podspec`:
```
s.test_spec 'Tests' do |test_spec|
   ...
   test_spec.dependency 'SwiftyMocky'
   test_spec.pod_target_xcconfig = {
     'OTHER_SWIFT_FLAGS' => '-D Mocky',
   }
end
```

`Podfile`:
```
target 'MyPodExample' do
  pod 'MyPod', :testspecs => ['Tests']
  
  pod 'SwiftyMocky/Prototyping'
end
```

(tests added as `testspecs` to the main target of the example app)

In this case, after installing the pod the main target of the example app has **both** `-DMocky` and `-DMockyCustom` in `Other Swift Flags`. 

It doesn't compile the `generated.swift` file of the example app because of `Type 'SwiftyMockyTestObserver' has no member 'handleMissingStubError'` in
```
private func onFatalFailure(_ message: String) {
        #if Mocky
        guard let file = self.file, let line = self.line else { return } // Let if fail if cannot handle gratefully
        SwiftyMockyTestObserver.handleMissingStubError(message: message, file: file, line: line)
        #endif
    }
```

I guess the main target of the example app should have **only** `-DMockyCustom` in `Other Swift Flags`.

**Comment by g-amichnia** [comment]
Hi, I will look into that. Good guess with that flags - I need to review it. The prototyping is still alpha, I think one of the ideas is to move it to separate repo, and have it done independently, since mock is mainly test oriented now.

**Comment by g-amichnia** [comment]
@maxxx777 we are splitting SwiftyMocky and SwityPrototype starting from version 4.0.0, that should solve your problem. Because of many reasons we are abandoning all the compilation flags.

**Comment by g-amichnia** [comment]
Integration test list to confirm issue can be closed
- [ ] Testing and prototyping with CocoaPods
- [ ] Testing and prototyping with Carthage
- [ ] Testing and prototyping with SwiftPM
