### ISSUE TITLE
Error on generate after install Xcode 12 Beta

### ISSUE THREAD

**Issue by Tavernari** [MakeAWishFoundation/SwiftyMocky#253]
Hi guys,

I installed an Xcode 12 beta version so after that I got an error when I run generate command.

If you check the message log, `Message:` is empty.

`SwiftyMocky CLI v3.5.0`

```Error: ShellOut encountered an error
Status code: 3
Message: ""
Output: "Using configuration file at '{project_path}/.mocky/.config.yml.tmp'
Scanning sources...
	loadOrParse: 0.3647400140762329
	resolution took 0.127344012260437
	combiningTypes: 0.1399979591369629
	total: 0.5072109699249268
Found 265 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.011709928512573242
Generating code...
error: "
```

Everyone knows how to read a log or knows how to resolve this issue? 

Thanks in advance.

**Comment by Tavernari** [comment]
Same error on `setup` command

**Comment by Tavernari** [comment]
Maybe I found the problem.

I ran the `swiftymocky generate -v` and I figured out the problem is with this command `xcrun swift build -Xswiftc -Onone -Xswiftc -suppress-warning  --disable-sandbox`, so the first problem is its was complaining about this project does not have `Package.swit` so I installed it, after that, it started complaining about `error: unable to load standard library for target 'x86_64-apple-macosx10.15'`. I think maybe the problem is because I have to install the new macOS beta to work.

**Comment by Tavernari** [comment]
I restarted my MacBook and works fine. I have no idea what happened

**Comment by g-amichnia** [comment]
Hi, no problem, we are not yet testing on beta software. Usually, problems arises with all the tools build with different sdk. IO think since swift 5 it should be abi stable, and thus shall work, but well, usually simple things like restart/uninstall and install solve problems :)

**Comment by g-amichnia** [comment]
Also, we are moving CLI to saparate repo, please file all issues for it on: https://github.com/MakeAWishFoundation/SwiftyMockyCLI
