### ISSUE TITLE
Default Mock.swifttemplate throwing empty error

### ISSUE THREAD

**Issue by jbehrens94** [MakeAWishFoundation/SwiftyMocky#255]
I've seen multiple issues on this specific topic. When I do a fresh 3.5.0 install of SwiftyMocky and Sourcery v0.18.0, I point Sourcery to the Pods folder with the SwiftyMocky Mock.swifttemplate. That template, also when copied manually to a Sourcery folder, throws an empty error and does not generate anything.

I've made sure that --disableCache doesn't solve the problem, as well as a reboot or clean caches from Xcode.

<img width="274" alt="Schermafbeelding 2020-07-16 om 21 03 23" src="https://user-images.githubusercontent.com/5713854/87711646-d679e500-c7a7-11ea-8c78-44f8f684b062.png">

<img width="322" alt="Schermafbeelding 2020-07-16 om 21 03 33" src="https://user-images.githubusercontent.com/5713854/87711620-d0840400-c7a7-11ea-9a35-98ccd0987824.png">

**Comment by jbehrens94** [comment]
Seems to be related to this issue on Sourcery: https://github.com/krzysztofzablocki/Sourcery/issues/817

Maybe it's worth it to rewrite the template in Stencil, as Sourcery's maintainers already mentioned how .swifttemplate files are a headache to them.

**Comment by Przemyslaw-Wosko** [comment]
@jbehrens94 instead going for stencil i'd love to go straight for https://github.com/apple/swift-syntax, and not bother with any more 3rd party, but that would require a lot of work. 
We would preserve original SwiftyMocky API, and just focus on reworking generation. Maybe someone want to help with that? ^^

**Comment by jbehrens94** [comment]
Sounds like an awesome thing to do, I'd love to help! :)

**Comment by g-amichnia** [comment]
I think a way to go would be to directly depend on Sourcery in our CLI. So there would be no more depending on the fact that Sourcery is installed or available, mixed versions, etc. We must investigate how easy it would be this way. 

I also like the ide to go directly with swift-syntax, but that might be just a bit too much to chew at once :)

Btw. @jbehrens94  SwiftyMocky version 4.0.0 is just out and fresh, you might consider trying it out. Closing this for now, as it does not seem there is much we can do about it at this point.

**Comment by fssilva** [comment]
Could we re-open this and bump the Sourcery version SwiftyMocky uses ? 
https://github.com/krzysztofzablocki/Sourcery/issues/817

**Comment by amichnia** [comment]
Should be fixed with 4.0.1

**Comment by pgorzelany-objectivity** [comment]
@amichnia how do we use Sourcery 1.0.0 with the old SwiftyMocky setup? Do we use the getSourcery script?

**Comment by amichnia** [comment]
> @amichnia how do we use Sourcery 1.0.0 with the old SwiftyMocky setup? Do we use the getSourcery script?

No, I think we stopped using that script after swift got abi stable. 

Anyway, it all depends on how you install sourcery. If you use pods, run pod update, mocky 4.0.1 already points to right binary. 

With the old set up, you just execute sourcery binary passing the path to config as an argument.
