### ISSUE TITLE
Variadic method parameter support

### ISSUE THREAD

**Issue by timwredwards** [MakeAWishFoundation/SwiftyMocky#256]
SwiftyMocky is a great Framework, but it doesn't currently support variadic methods, with a variable number of method parameters:

```swift
    open func methodWithVadiadicParameter(_ parameter: String...) {
        addInvocation(.m_methodWithVadiadicParameter__parameter(Parameter<String>.value(`parameter`)))
		let perform = methodPerformValue(.m_methodWithVadiadicParameter__parameter(Parameter<String>.value(`parameter`))) as? (String) -> Void
		perform?(`parameter`)
    }
```

As you can see, SwiftyMocky interprets the parameter type as String rather than [String].

I've done some digging and it looks like Sourcery also doesn't support variadic notation `...`, and doesn't forward this information onto SwiftyMocky, but it would be valuable to have some further input from a SwiftyMocky core contributor before deciding on a way forward.

**Comment by timwredwards** [comment]
I've got around this by redeclaring the protocol in my test target, and redefining the method with an Array parameter rather than variadic. I then created an extension to the Mock which forwards the variadic method call to the Mocked method call with the array parameter. It does work but it's very ugly and verbose, it would be good to see if we can properly support variadic parameters via Sourcery in the future.

**Comment by timwredwards** [comment]
After further investigation, it seems SourceKitten, and I guess hence SourceKit is not actually sending variadic information to Sourcery - so the only way I can think of supporting this is to do some hacky string parsing on the method. Another option is to provide an annotation to Sourcery to manually replace the Parameter type with an array.

**Comment by g-amichnia** [comment]
Thanks for your insightful comment. I see two ways to do it now:
1. We would do same thing as with generics, as long as Sourcery and SourceKitten properly identifies methods with variadic parameters. Then we can treat it as arrays.
2. For some reason it would be not possible - we will provide annotation. I would rather not do it, as these annotations are hard to discover and it requires going through full documentation to find it.

**Comment by timwredwards** [comment]
> Thanks for your insightful comment. I see two ways to do it now:

You're welcome - thank you for creating such a useful framework.

> 1. We would do same thing as with generics, as long as Sourcery and SourceKitten properly identifies methods with variadic parameters. Then we can treat it as arrays.

I haven't yet delved into the way you deal with generics, but it seems as though Sourcery.Method.Name retains the `...` notation, and so it would be theoretically possible to extract variadic parameters through String parsing within SwiftyMocky.

> 2. For some reason it would be not possible - we will provide annotation. I would rather not do it, as these annotations are hard to discover and it requires going through full documentation to find it.

I agree, using annotations solution is less-than-ideal.

**Comment by timwredwards** [comment]
This may come in useful for extracting the variadic parameter from a method name:
```swift
    func getVariadicParameterNameFromMethodName(_ methodName: String) -> String? {
      guard
        let variadicRange = methodName.range(of: "..."),
        let colonIndex = methodName[...variadicRange.lowerBound].lastIndex(of: ":"),
        let spaceIndex = methodName[...colonIndex].lastIndex(of: " ") else {
          return nil
      }
      return String(method.name[methodName.index(after: spaceIndex)..<colonIndex])
    }
```

**Comment by amichnia** [comment]
@timwredwards Thanks for the snippet. I had to modify it a bit to cover some really silly cases, like '[A: B]...'
