### ISSUE TITLE
Mocks of protocools with mutating methods don't compile

### ISSUE THREAD

**Issue by kubamatula** [MakeAWishFoundation/SwiftyMocky#262]
**SwiftyMockyCLI version 4.0.0.**

Mocks generated for protocools with mutating methods don't compile, because of `mutating` modifier in static functions, and `mutating` modifier used in the class implementation of the protocool.

An example protocool for which CLI generated mock doesn't compile:
```
public protocol SomeProtocool: AutoMockable {
    mutating func exampleMutatingFunc()
}
```

**Comment by g-amichnia** [comment]
Fixed
