### ISSUE TITLE
Mocks for `available(iOS xxx)` build error with Stubber variant  

### ISSUE THREAD

**Issue by JiceDessaint** [MakeAWishFoundation/SwiftyMocky#264]
SwiftyMocky 4.0.1 (Cocoapods integration) + SwiftymockyCLI 4.0.1

Got an error when mocking following protocol: 
```swift
//sourcery: AutoMockable
protocol SomeProtocol {
    @available(iOS 12.0, *)
    func funcA() -> String
}
```
will produce following code for stubbing method:
```swift
        @available(iOS 12.0, *)
	public static func funcA(willReturn: String...) -> MethodStub { ... }
        public static func funcA(willProduce: (Stubber<String>) -> Void) -> MethodStub {
               // Missing @available
        }
```
`willReturn` variant is good, but `stubber` version miss the available annotation, resulting in compilation error `'m_funcA' is only available in iOS 12.0 or newer`

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/7337081/94286834-d3446780-ff55-11ea-993c-09511bc6ae8d.png">

**Comment by g-amichnia** [comment]
Fixed.
