### ISSUE TITLE
Unreliable matching of unordered Sequence parameters

### ISSUE THREAD

**Issue by tarbayev** [MakeAWishFoundation/SwiftyMocky#268]
Current implementation treats `Sequence` parameters as ordered collections, while the order of the elements is not guaranteed.
This leads to random failures in matching `Dictionary` and other unordered collection parameters.

**Comment by g-amichnia** [comment]
Changed, currently only Arrays are treated as ordered sequences. For all behaviours that are non-default, please override comparator for that specific sequence type.
