### ISSUE TITLE
Link error with Xcode 12.5 Beta 2

### ISSUE THREAD

**Issue by pmanuelli** [MakeAWishFoundation/SwiftyMocky#277]
Hello!

I have integrated SwiftyMocky `4.0.3`. With Xcode 12.5 beta 2 the project no longer links. 

When SwiftyMocky is linking it gives an error: `ld: library not found for -lswiftXCTest`

The [Xcode 12.5 beta Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-beta-release-notes) reads:

> Deprecations
> Xcode no longer includes XCTest’s legacy Swift overlay library (libswiftXCTest.dylib). Use the library’s replacement, libXCTestSwiftSupport.dylib, instead. For frameworks that link XCTest and encounter build issues due to this removed legacy library, replace those frameworks’ manual framework and library search paths with the build setting ENABLE_TESTING_SEARCH_PATHS=YES, which automatically configures the target with the search paths needed to locate XCTest libraries. (70365050)

Thank you!

**Comment by polmum** [comment]
Hi!
I'm having the same issue. Updating the podspec's line `'OTHER_LDFLAGS' => '$(inherited) -weak-lswiftXCTest -Xlinker -no_application_extension'` by removing the `-weak-lswiftXCTest` linkage appears to fix the issue. I also tried replacing it with `-weak-lXCTestSwiftSupport`, and it worked as well.

**Comment by g-amichnia** [comment]
Will be released with 4.0.4, thanks to @emn-mun fix. Closing

**Comment by rserentill** [comment]
Hello @g-amichnia, any news on this? when is version 4.0.4 planned to be released?
