### ISSUE TITLE
Does it support mocking protocols using RxSwift?

### ISSUE THREAD

**Issue by abhilashRakuten** [MakeAWishFoundation/SwiftyMocky#284]
I am getting so many errors with the Mock.generated file while trying to mock a protocol written using RxSwift and RxCocoa.  Is it supported?

**Comment by erneestoc** [comment]
Yes, just make sure you added `RxSwift` to the imports on your `Mockfile`

**Comment by g-amichnia** [comment]
Yes, as @erneestoc mentioned, update a Mockfile / legacy yaml file to make sure all imports are there.
