### ISSUE TITLE
Generic any value comparison failure

### ISSUE THREAD

**Issue by devturhan** [MakeAWishFoundation/SwiftyMocky#287]
Hey, first I would like to thank you for your great effort in this project. 

After we update SwiftMocky to 4.0.4 and Xcode 12.5, some of our tests are started to failing. 
Failing tests are occurring due to a failure on comparison of Generic closure (T->Void). When I dig into it, I found that comparison is failing because the wrapAsGeneric function converts it as Parameter with GenericAttribute, and its comparison closure returning false even we pass it as Parameter.any to the perform function.

<img width="1630" alt="Screen Shot 2021-06-11 at 23 59 28" src="https://user-images.githubusercontent.com/26139447/121750738-9fc26100-cb15-11eb-80bf-6621e764e86a.png">

As you can see in the screenshot LHS parameter is actually Parameter.any but converted to .value by wrapAsGeneric function during perform function execution and compare closure in GenericAttribute returns false which is resulting test failure. 
What is the reason for converting Parameter.any value as Parameter.value in wrapAsGeneric function and why compare closure just not returns true for Parameter.any values? 

Thanks,
Ömer

**Comment by amichnia** [comment]
Working on it. Thanks for raising.

**Comment by g-amichnia** [comment]
Added tests, seems it works properly in 4.1.

Just one remark about generics, not sure if applies here. In general, they are type sensitive, in a way, that is not always `.any == .any`.  In other words:

```swift
// Call 
mock.methodWithGenericClosure(closure: { String -> Void in /* nothing */ }) // T resolves to (String) -> Void
// Verify
Verivy(mock, .methodWithGenericClosure(closure: .any((String) -> Void)) // SUCCESS, matches
Verivy(mock, .methodWithGenericClosure(closure: .any((BaseApiResponse) -> Void)) // FAILURE, does not matches
```

This is intended.
