### ISSUE TITLE
Couldn't clone https://github.com/MakeAWishFoundation/SwiftyMocky.git

### ISSUE THREAD

**Issue by nareksedrakyan** [MakeAWishFoundation/SwiftyMocky#291]
mint install MakeAWishFoundation/SwiftyMocky@3.4.0 --verbose
🌱 Cloning SwiftyMocky 3.4.0
Cloning into 'github.com_MakeAWishFoundation_SwiftyMocky'...
kex_exchange_identification: read: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
🌱 Encountered error during "git clone --depth 1 -b 3.4.0 https://github.com/MakeAWishFoundation/SwiftyMocky.git github.com_MakeAWishFoundation_SwiftyMocky"
🌱  Couldn't clone https://github.com/MakeAWishFoundation/SwiftyMocky.git 3.4.0

**Comment by isaac-weisberg** [comment]
Doesn't look like an issue with the framework. Your network connectivity just fails for reasons unbeknownst.
