### ISSUE TITLE
How about packaging a build of SwiftyMocky CLI right inside the runtime library package/pod?

### ISSUE THREAD

**Issue by isaac-weisberg** [MakeAWishFoundation/SwiftyMocky#292]
So you could expect `./Pods/SwiftyMocky` to contain a directory called `bin` which would contain `swiftymocky` executable.

This has several advantages:
- installation process is shortened by half of the steps
- no need to depend on Homebrew or Mint
- the versions between CLI and the runtime library are strictly aligned, you update one - you update the other, and you can not achieve a situation where a deployed project behaves unexpectedly due to the CLI version being different on someones setup

This has a disadvantage:
- it requires work to be done, you actually have to do something to implement this suggestion

**Comment by g-amichnia** [comment]
Will do!

**Comment by g-amichnia** [comment]
Should be done in 4.1
