### ISSUE TITLE
Comparator for dictionaries unordered parameters

### ISSUE THREAD

**Issue by laspowa** [MakeAWishFoundation/SwiftyMocky#294]
The order of elements is not guaranteed but comparator treats [String: Any] as ordered sequence what leads to flaky tests. Already saw other issues - didn't help. 

I have registered:
Matcher.default.register((key: String, value: Any).self) { lhs, rhs in
            guard let lhs1 = lhs.value as? String else { return false }
            guard let rhs1 = rhs.value as? String else { return false }
            return lhs.key == rhs.key && lhs1 == rhs1
        }

BUT it works only with fixes in Parameter.swift to check the whole sequence. All tests passed.
<img width="690" alt="Снимок экрана 2021-08-23 в 15 11 40" src="https://user-images.githubusercontent.com/26014030/130445049-bcc47d44-88ad-4041-931a-10f0f126d737.png">

**Comment by g-amichnia** [comment]
Fixed in 4.1
