### ISSUE TITLE
Linked documentation isn't human readable (wrong Content-Type)

### ISSUE THREAD

**Issue by chkpnt** [MakeAWishFoundation/SwiftyMocky#296]
In case you haven't noticed: The linked [documentation](https://cdn.rawgit.com/MakeAWishFoundation/SwiftyMocky/4.1.0-pre/docs/index.html) in the README is delivered by the CDN as `text/plain` leading to this experience:

<img width="1250" alt="grafik" src="https://user-images.githubusercontent.com/1956979/136830349-af9b659a-c97d-44c7-95ae-6f27f003369c.png">

**Comment by amichnia** [comment]
Fixed
