### ISSUE TITLE
No registered comparators for Any issue.

### ISSUE THREAD

**Issue by ArturKvaratshelia** [MakeAWishFoundation/SwiftyMocky#298]
Hello, I have protocol with generic method.
```
protocol Storage {
    func write(value: Any, for key: String)
}
```
but when I try to compare parameter with bool type
`storageMock.verify(.write(value: .value(true), for: .value("Key")), count: 1)`
I have received error `No registered comparators for Any`.

![Screenshot 2021-11-10 at 10 50 09](https://user-images.githubusercontent.com/49284155/141083361-61a3eaed-06a0-40ba-922f-ed0007500760.png)

Do you know workaround for this issue?

Environment:
```
cocoapods
'Quick', '~> 4.0.0'
'Nimble', '~> 9.2.1'
'SwiftyMocky', '4.1.0'
```

**Comment by spaluchiewicz** [comment]
@ArturKvaratshelia have you tried register the `comparator` according to the documentation: https://rawcdn.githack.com/MakeAWishFoundation/SwiftyMocky/4.1.0/docs/matcher-support-for-not-equatable.html ?

**Comment by ArturKvaratshelia** [comment]
@spaluchiewicz  Thanks. This is what I was looking for.
