### ISSUE TITLE
generate from pod does not work

### ISSUE THREAD

**Issue by dkk** [MakeAWishFoundation/SwiftyMocky#325]
generate throws an error. 

Notes: 
* `setup` was already executed and executing it again shows the `⚠️  Mockfile™ already exists.` warning.
* The sourcery command does exist at the given path.

**My System:**
```
Model Name: MacBook Pro (16-Inch, 2021)
Model Identifier: MacBookPro18,1
Chip: Apple M1 Pro
Total Number of Cores: 10 (8 performance and 2 efficiency)
Memory: 32 GB
System Firmware Version: 7459.141.1
OS: macOS Monterey (12.6)
Xcode: 14.0
```

**Output:**
```
╰─ ./Pods/SwiftyMocky/bin/swiftymocky generate
╔════════════════════════╗
║ SwiftyMocky CLI v4.1.0 ║
╚════════════════════════╝

Running at: /XXX
Using template from Cocoapods
Processing mock: mocky ...
Using sourcery command: /XXX/Pods/Sourcery/bin/sourcery
Using configuration file at '/XXX/.mocky75DA13CD-2E9F-484B-B6BF-35749AB69499/.config.yml.tmp'
Scanning sources...
Found 135 types in 72 files, 0 changed from last run.
Loading templates...
Loaded 1 templates.
Generating code...
error: error: '1.6.0': Invalid manifest
/private/var/folders/kf/qp0y69697clfgygh_gckx9f40000gq/T/SwiftTemplate/1.6.0/Package.swift:4:8: error: no such module 'PackageDescription'
import PackageDescription
       ^

❌  Error: ShellOut encountered an error
Status code: 3
Message: "error: '1.6.0': Invalid manifest
/private/var/folders/kf/qp0y69697clfgygh_gckx9f40000gq/T/SwiftTemplate/1.6.0/Package.swift:4:8: error: no such module 'PackageDescription'
import PackageDescription
       ^"
Output: "Using configuration file at '/XXX/.mocky75DA13CD-2E9F-484B-B6BF-35749AB69499/.config.yml.tmp'
Scanning sources...
Found 135 types in 72 files, 0 changed from last run.
Loading templates...
Loaded 1 templates.
Generating code...
error: error: '1.6.0': Invalid manifest
/private/var/folders/kf/qp0y69697clfgygh_gckx9f40000gq/T/SwiftTemplate/1.6.0/Package.swift:4:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
"
```

**Comment by dkk** [comment]
May be related to https://github.com/MakeAWishFoundation/SwiftyMocky/issues/311

**Comment by dkk** [comment]
May be related to https://github.com/MakeAWishFoundation/SwiftyMocky/issues/309

**Comment by dkk** [comment]
Note that pod update currently does not download 4.2.0 since [there is no updated spec](https://github.com/MakeAWishFoundation/SwiftyMocky/issues/322). However, note that using:
```
  pod 'SwiftyMocky', '4.1.0'
  pod 'Sourcery', '1.6.0' 
```
has the same outcome

**Comment by dkk** [comment]
It seems that it was a general problem with my Xcode Command Line Tools setup. Running `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` solved the issue.

**Comment by dkk** [comment]
Btw. I changed my Podfile to:
```
  pod 'SwiftyMocky', :git => 'https://github.com/MakeAWishFoundation/SwiftyMocky.git', :tag => '4.2.0'
  pod 'Sourcery', '1.8.0'
```

**Comment by mannyvw** [comment]
Am having same problem, forced pod to update to 4.1.0 and made the sudo xcode-select -s /Applications/Xcode.app/Contents/Developer call. still the same problem 

❌  Error: ShellOut encountered an error
Status code: 3

Did the last thing you mentioned 

```
pod 'SwiftyMocky', :git => 'https://github.com/MakeAWishFoundation/SwiftyMocky.git', :tag => '4.2.0'
pod 'Sourcery', '1.8.0'
```

Now get ./Pods/SwiftyMocky/bin/swiftymocky: Bad CPU type in executable, mmm

**Comment by dkk** [comment]
Maybe try to completely clean and rebuild your Pods project:
```
pod deintegrate
rm Podfile.lock
pod install
```

**Comment by VilemKurz** [comment]
Interesting, 4.1.0 works for me on intel without any additional setup. Tested on both Xcode 14 GM (via xcodes) and Xcode 13.4.1 on the default location
