### ISSUE TITLE
Skip protocols that cannot be generated with warning

### ISSUE THREAD

**Issue by amichnia** [MakeAWishFoundation/SwiftyMocky#62]
Similar as in R.swift - we want to value stability. For protocols that cannot be mocked for some reason - we want to skip generation, and show warning with detailed description.

**Comment by Przemyslaw-Wosko** [comment]
I found way to leave warinings in console, when building project, but there is really hard to make it from swifttemplate. This needs to wait till we find a way to move some swift code from swifttemplate file, to be able to rise those warnings.

**Comment by amichnia** [comment]
Iceboxing for now. There is no actual way to approach that now, and not much reason to do.
