### ISSUE TITLE
Articles about SwiftyMocky

### ISSUE THREAD

**Issue by Przemyslaw-Wosko** [MakeAWishFoundation/SwiftyMocky#68]
We have quite good documentation, but we need articles that will introduce new users to concept of using this library. 
I'd be nice to prepare following articles: 
- Unit testing on iOS, best practices, how to write code to be testable 
- SwiftyMocky - how to use it, how to start, live coding video? 
- Comparison SwiftyMocky vs Cuckoo 

@amichnia what do you think?

**Comment by amichnia** [comment]
All seems fine to me. I’ll probably go for number 2 myself if that fits you.
