### ISSUE TITLE
Facing issue while running SwiftyMocky (both 0.9.0 & 1.0.0) in XCode 9

### ISSUE THREAD

**Issue by PoorvaSingh09** [MakeAWishFoundation/SwiftyMocky#69]
XCode 9 gives compile time error when built with SwiftyMocky.
![mocky_error](https://user-images.githubusercontent.com/29882598/33012575-62d45226-ce07-11e7-8c3c-178b31d0f621.png)

**Comment by amichnia** [comment]
@PoorvaSingh09 - could you provide error message? Looking into that

**Comment by PoorvaSingh09** [comment]
Ambiguous use of 'compare(lhs:rhs:with:)'
<img width="255" alt="screen shot 2017-11-20 at 3 51 57 pm" src="https://user-images.githubusercontent.com/29882598/33013657-d4643b92-ce0a-11e7-9f6a-20671bcb5958.png">
<img width="971" alt="screen shot 2017-11-20 at 3 52 08 pm" src="https://user-images.githubusercontent.com/29882598/33013658-d4ad7f1e-ce0a-11e7-84a3-a7b6d47afd35.png">

**Comment by amichnia** [comment]
Ok, it seems it's and error with Swift < 4, where  parameter is both Sequence and Equatable. I'll upload fix and we'll go with 1.0.1 i think today. Thanks for info - will keep you informed.

**Comment by amichnia** [comment]
@PoorvaSingh09 - we just released version 1.0.1, should fix the issue: https://cocoapods.org/pods/SwiftyMocky

Closing.
