### ISSUE TITLE
Update testing on for older Swift versions.

### ISSUE THREAD

**Issue by amichnia** [MakeAWishFoundation/SwiftyMocky#71]
At this point, our travis runs tests with same config as whole example project, so Swift 4 etc.

We might need environment, to constantly verify, if our setup is also valid for swift versions 3.x

**Comment by amichnia** [comment]
Removing from project scope, as it is not exclusive for any SwiftyMocky version.

**Comment by amichnia** [comment]
I think we will look into that later, dropping from 3.0 for now. It's mainly maintenance and automation, so could be done after release

**Comment by Przemyslaw-Wosko** [comment]
Regarding #154, i'm adding it here as reminder

**Comment by amichnia** [comment]
Added matrix for Travis CI, we will cover swift 4.0, 4.2, 5.0
