### ISSUE TITLE
Version 1.0.1 not working with XCode 8.3

### ISSUE THREAD

**Issue by PoorvaSingh09** [MakeAWishFoundation/SwiftyMocky#83]
After upgrading to version 1.0.1, it works fine with XCode 9 but fails with XCode 8.3. Aren't we supporting backward compatibility?

<img width="1279" alt="screen shot 2017-11-21 at 12 41 52 pm" src="https://user-images.githubusercontent.com/29882598/33059258-86a3e812-ceb9-11e7-899a-1130755da9db.png">

**Comment by amichnia** [comment]
Is it XCode 8.3 or 8.3.3 ?

**Comment by amichnia** [comment]
Anyway - downloading XCode 8.3 and checking. Will probably have some info later today

**Comment by PoorvaSingh09** [comment]
Hi Andrzej,

It was xcode 8.3.3

Thanks & Regards,
Poorva

On 21-Nov-2017, at 6:29 PM, Andrzej Michnia <notifications@github.com<mailto:notifications@github.com>> wrote:

[Email from a non-Nagarro source: please exercise caution with links and attachments]


Anyway - downloading XCode 8.3 and checking. Will probably have some info later today

**Comment by amichnia** [comment]
@PoorvaSingh09 - problem seems to be solved now, will release 1.0.2 with fixes.
