### ISSUE TITLE
Invocations count

### ISSUE THREAD

**Issue by Przemyslaw-Wosko** [MakeAWishFoundation/SwiftyMocky#93]
Currently we can just describe how many invocations we are expecting. 

```
func Verify<T: Mock>(_ object: T, _ count: UInt, _ method: T.Verify, file: StaticString = #file, line: UInt = #line)
```
We need to add ranges, for instance: 
- at least once 
- never
- moreThan
- lessThan

**Comment by amichnia** [comment]
done
