### ISSUE TITLE
Can’t generate mock for generics with type

### ISSUE THREAD

**Issue by andlang** [MakeAWishFoundation/SwiftyMocky#97]
Hi,

I have an issue when I try to generate a mock from a protocol that has a function like the following:
```swift
func decode<T: Decodable>(_ type: T.Type, from data: Data) -> T
```
Due to the `.Type` the generic is lost in the generation.

Do you know about this? And does a workaround exist?

**Comment by amichnia** [comment]
Checking that, we might have issues with `.Type` - if so, I'll start fixing it right away. Thanks for the info.

**Comment by amichnia** [comment]
@andlang - I have fixed that issue, its waiting for code review. I think it will not be released as 1.3 bug fix, but along with version 2.0, which should be available in next few days. Updating release date for the end of the week, but it might be sooner.

In general, that how the test added looks like now. Please note, that there is a requirement to register all custom Type's in order of matcher working fine. Also - in that particular case there is literally no difference between using .value and .any for T.Type attribute.

```swift
func test_custom_type_constraint() {
        let mock = GenericProtocolWithTypeConstraintMock()

        let data = Data()
        let otherData = Data(count: 20)
        XCTAssertNotEqual(data, otherData)

        // Required to allow Type matching! Basic types like Int.self, Bool.self etc have already registered comparators
        Matcher.default.register(CustomThing.Type.self)

        Given(mock, .decode(type: .value(Int.self), from: .any, willReturn: 0))
        Given(mock, .decode(type: .value(Int.self), from: .value(data), willReturn: 1))
        Given(mock, .decode(type: .any(CustomThing.Type.self), from: .any, willReturn: CustomThing(id: 0)))
        Given(mock, .decode(type: .any(CustomThing.Type.self), from: .value(data), willReturn: CustomThing(id: 1)))

        XCTAssertEqual(mock.decode(Int.self, from: otherData), 0)
        XCTAssertEqual(mock.decode(Int.self, from: data), 1)

        XCTAssertEqual(mock.decode(CustomThing.self, from: otherData).id, 0)
        XCTAssertEqual(mock.decode(CustomThing.self, from: data).id, 1)
}
```

**Comment by amichnia** [comment]
@andlang  - quick update, code get merged. New version will be available this week I think. I'm marking issue as done.

**Comment by andlang** [comment]
Perfect, it works! Thank you very much!

**Comment by amichnia** [comment]
@andlang Version 2.0 is ready, feel free to check it out :)
